// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: bill/v1/bill.proto

package com.didiyun.bill.v1;

/**
 * Protobuf type {@code didi.cloud.bill.v1.ChargeInfo}
 */
public  final class ChargeInfo extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:didi.cloud.bill.v1.ChargeInfo)
    ChargeInfoOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ChargeInfo.newBuilder() to construct.
  private ChargeInfo(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ChargeInfo() {
    endTime_ = 0L;
    costThisMonth_ = 0D;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private ChargeInfo(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            endTime_ = input.readInt64();
            break;
          }
          case 17: {

            costThisMonth_ = input.readDouble();
            break;
          }
          case 26: {
            if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
              chargeInfo_ = com.google.protobuf.MapField.newMapField(
                  ChargeInfoDefaultEntryHolder.defaultEntry);
              mutable_bitField0_ |= 0x00000004;
            }
            com.google.protobuf.MapEntry<java.lang.String, com.didiyun.bill.v1.FactorRuleDetail>
            chargeInfo__ = input.readMessage(
                ChargeInfoDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
            chargeInfo_.getMutableMap().put(
                chargeInfo__.getKey(), chargeInfo__.getValue());
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.didiyun.bill.v1.BillOuterClass.internal_static_didi_cloud_bill_v1_ChargeInfo_descriptor;
  }

  @SuppressWarnings({"rawtypes"})
  @java.lang.Override
  protected com.google.protobuf.MapField internalGetMapField(
      int number) {
    switch (number) {
      case 3:
        return internalGetChargeInfo();
      default:
        throw new RuntimeException(
            "Invalid map field number: " + number);
    }
  }
  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.didiyun.bill.v1.BillOuterClass.internal_static_didi_cloud_bill_v1_ChargeInfo_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.didiyun.bill.v1.ChargeInfo.class, com.didiyun.bill.v1.ChargeInfo.Builder.class);
  }

  private int bitField0_;
  public static final int ENDTIME_FIELD_NUMBER = 1;
  private long endTime_;
  /**
   * <pre>
   *只适用于包月时
   * </pre>
   *
   * <code>int64 endTime = 1;</code>
   */
  public long getEndTime() {
    return endTime_;
  }

  public static final int COSTTHISMONTH_FIELD_NUMBER = 2;
  private double costThisMonth_;
  /**
   * <pre>
   *本月用量，如为包月，则为包月按比例的消耗
   * </pre>
   *
   * <code>double costThisMonth = 2;</code>
   */
  public double getCostThisMonth() {
    return costThisMonth_;
  }

  public static final int CHARGEINFO_FIELD_NUMBER = 3;
  private static final class ChargeInfoDefaultEntryHolder {
    static final com.google.protobuf.MapEntry<
        java.lang.String, com.didiyun.bill.v1.FactorRuleDetail> defaultEntry =
            com.google.protobuf.MapEntry
            .<java.lang.String, com.didiyun.bill.v1.FactorRuleDetail>newDefaultInstance(
                com.didiyun.bill.v1.BillOuterClass.internal_static_didi_cloud_bill_v1_ChargeInfo_ChargeInfoEntry_descriptor, 
                com.google.protobuf.WireFormat.FieldType.STRING,
                "",
                com.google.protobuf.WireFormat.FieldType.MESSAGE,
                com.didiyun.bill.v1.FactorRuleDetail.getDefaultInstance());
  }
  private com.google.protobuf.MapField<
      java.lang.String, com.didiyun.bill.v1.FactorRuleDetail> chargeInfo_;
  private com.google.protobuf.MapField<java.lang.String, com.didiyun.bill.v1.FactorRuleDetail>
  internalGetChargeInfo() {
    if (chargeInfo_ == null) {
      return com.google.protobuf.MapField.emptyMapField(
          ChargeInfoDefaultEntryHolder.defaultEntry);
    }
    return chargeInfo_;
  }

  public int getChargeInfoCount() {
    return internalGetChargeInfo().getMap().size();
  }
  /**
   * <pre>
   *当前此资源的计费信息.key为计费项factor
   * </pre>
   *
   * <code>map&lt;string, .didi.cloud.bill.v1.FactorRuleDetail&gt; chargeInfo = 3;</code>
   */

  public boolean containsChargeInfo(
      java.lang.String key) {
    if (key == null) { throw new java.lang.NullPointerException(); }
    return internalGetChargeInfo().getMap().containsKey(key);
  }
  /**
   * Use {@link #getChargeInfoMap()} instead.
   */
  @java.lang.Deprecated
  public java.util.Map<java.lang.String, com.didiyun.bill.v1.FactorRuleDetail> getChargeInfo() {
    return getChargeInfoMap();
  }
  /**
   * <pre>
   *当前此资源的计费信息.key为计费项factor
   * </pre>
   *
   * <code>map&lt;string, .didi.cloud.bill.v1.FactorRuleDetail&gt; chargeInfo = 3;</code>
   */

  public java.util.Map<java.lang.String, com.didiyun.bill.v1.FactorRuleDetail> getChargeInfoMap() {
    return internalGetChargeInfo().getMap();
  }
  /**
   * <pre>
   *当前此资源的计费信息.key为计费项factor
   * </pre>
   *
   * <code>map&lt;string, .didi.cloud.bill.v1.FactorRuleDetail&gt; chargeInfo = 3;</code>
   */

  public com.didiyun.bill.v1.FactorRuleDetail getChargeInfoOrDefault(
      java.lang.String key,
      com.didiyun.bill.v1.FactorRuleDetail defaultValue) {
    if (key == null) { throw new java.lang.NullPointerException(); }
    java.util.Map<java.lang.String, com.didiyun.bill.v1.FactorRuleDetail> map =
        internalGetChargeInfo().getMap();
    return map.containsKey(key) ? map.get(key) : defaultValue;
  }
  /**
   * <pre>
   *当前此资源的计费信息.key为计费项factor
   * </pre>
   *
   * <code>map&lt;string, .didi.cloud.bill.v1.FactorRuleDetail&gt; chargeInfo = 3;</code>
   */

  public com.didiyun.bill.v1.FactorRuleDetail getChargeInfoOrThrow(
      java.lang.String key) {
    if (key == null) { throw new java.lang.NullPointerException(); }
    java.util.Map<java.lang.String, com.didiyun.bill.v1.FactorRuleDetail> map =
        internalGetChargeInfo().getMap();
    if (!map.containsKey(key)) {
      throw new java.lang.IllegalArgumentException();
    }
    return map.get(key);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (endTime_ != 0L) {
      output.writeInt64(1, endTime_);
    }
    if (costThisMonth_ != 0D) {
      output.writeDouble(2, costThisMonth_);
    }
    com.google.protobuf.GeneratedMessageV3
      .serializeStringMapTo(
        output,
        internalGetChargeInfo(),
        ChargeInfoDefaultEntryHolder.defaultEntry,
        3);
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (endTime_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(1, endTime_);
    }
    if (costThisMonth_ != 0D) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(2, costThisMonth_);
    }
    for (java.util.Map.Entry<java.lang.String, com.didiyun.bill.v1.FactorRuleDetail> entry
         : internalGetChargeInfo().getMap().entrySet()) {
      com.google.protobuf.MapEntry<java.lang.String, com.didiyun.bill.v1.FactorRuleDetail>
      chargeInfo__ = ChargeInfoDefaultEntryHolder.defaultEntry.newBuilderForType()
          .setKey(entry.getKey())
          .setValue(entry.getValue())
          .build();
      size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, chargeInfo__);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.didiyun.bill.v1.ChargeInfo)) {
      return super.equals(obj);
    }
    com.didiyun.bill.v1.ChargeInfo other = (com.didiyun.bill.v1.ChargeInfo) obj;

    boolean result = true;
    result = result && (getEndTime()
        == other.getEndTime());
    result = result && (
        java.lang.Double.doubleToLongBits(getCostThisMonth())
        == java.lang.Double.doubleToLongBits(
            other.getCostThisMonth()));
    result = result && internalGetChargeInfo().equals(
        other.internalGetChargeInfo());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ENDTIME_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getEndTime());
    hash = (37 * hash) + COSTTHISMONTH_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getCostThisMonth()));
    if (!internalGetChargeInfo().getMap().isEmpty()) {
      hash = (37 * hash) + CHARGEINFO_FIELD_NUMBER;
      hash = (53 * hash) + internalGetChargeInfo().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.didiyun.bill.v1.ChargeInfo parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.didiyun.bill.v1.ChargeInfo parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.didiyun.bill.v1.ChargeInfo parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.didiyun.bill.v1.ChargeInfo parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.didiyun.bill.v1.ChargeInfo parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.didiyun.bill.v1.ChargeInfo parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.didiyun.bill.v1.ChargeInfo parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.didiyun.bill.v1.ChargeInfo parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.didiyun.bill.v1.ChargeInfo parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.didiyun.bill.v1.ChargeInfo parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.didiyun.bill.v1.ChargeInfo parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.didiyun.bill.v1.ChargeInfo parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.didiyun.bill.v1.ChargeInfo prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code didi.cloud.bill.v1.ChargeInfo}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:didi.cloud.bill.v1.ChargeInfo)
      com.didiyun.bill.v1.ChargeInfoOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.didiyun.bill.v1.BillOuterClass.internal_static_didi_cloud_bill_v1_ChargeInfo_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapField internalGetMapField(
        int number) {
      switch (number) {
        case 3:
          return internalGetChargeInfo();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapField internalGetMutableMapField(
        int number) {
      switch (number) {
        case 3:
          return internalGetMutableChargeInfo();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.didiyun.bill.v1.BillOuterClass.internal_static_didi_cloud_bill_v1_ChargeInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.didiyun.bill.v1.ChargeInfo.class, com.didiyun.bill.v1.ChargeInfo.Builder.class);
    }

    // Construct using com.didiyun.bill.v1.ChargeInfo.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      endTime_ = 0L;

      costThisMonth_ = 0D;

      internalGetMutableChargeInfo().clear();
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.didiyun.bill.v1.BillOuterClass.internal_static_didi_cloud_bill_v1_ChargeInfo_descriptor;
    }

    @java.lang.Override
    public com.didiyun.bill.v1.ChargeInfo getDefaultInstanceForType() {
      return com.didiyun.bill.v1.ChargeInfo.getDefaultInstance();
    }

    @java.lang.Override
    public com.didiyun.bill.v1.ChargeInfo build() {
      com.didiyun.bill.v1.ChargeInfo result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.didiyun.bill.v1.ChargeInfo buildPartial() {
      com.didiyun.bill.v1.ChargeInfo result = new com.didiyun.bill.v1.ChargeInfo(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      result.endTime_ = endTime_;
      result.costThisMonth_ = costThisMonth_;
      result.chargeInfo_ = internalGetChargeInfo();
      result.chargeInfo_.makeImmutable();
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.didiyun.bill.v1.ChargeInfo) {
        return mergeFrom((com.didiyun.bill.v1.ChargeInfo)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.didiyun.bill.v1.ChargeInfo other) {
      if (other == com.didiyun.bill.v1.ChargeInfo.getDefaultInstance()) return this;
      if (other.getEndTime() != 0L) {
        setEndTime(other.getEndTime());
      }
      if (other.getCostThisMonth() != 0D) {
        setCostThisMonth(other.getCostThisMonth());
      }
      internalGetMutableChargeInfo().mergeFrom(
          other.internalGetChargeInfo());
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.didiyun.bill.v1.ChargeInfo parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.didiyun.bill.v1.ChargeInfo) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private long endTime_ ;
    /**
     * <pre>
     *只适用于包月时
     * </pre>
     *
     * <code>int64 endTime = 1;</code>
     */
    public long getEndTime() {
      return endTime_;
    }
    /**
     * <pre>
     *只适用于包月时
     * </pre>
     *
     * <code>int64 endTime = 1;</code>
     */
    public Builder setEndTime(long value) {
      
      endTime_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *只适用于包月时
     * </pre>
     *
     * <code>int64 endTime = 1;</code>
     */
    public Builder clearEndTime() {
      
      endTime_ = 0L;
      onChanged();
      return this;
    }

    private double costThisMonth_ ;
    /**
     * <pre>
     *本月用量，如为包月，则为包月按比例的消耗
     * </pre>
     *
     * <code>double costThisMonth = 2;</code>
     */
    public double getCostThisMonth() {
      return costThisMonth_;
    }
    /**
     * <pre>
     *本月用量，如为包月，则为包月按比例的消耗
     * </pre>
     *
     * <code>double costThisMonth = 2;</code>
     */
    public Builder setCostThisMonth(double value) {
      
      costThisMonth_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *本月用量，如为包月，则为包月按比例的消耗
     * </pre>
     *
     * <code>double costThisMonth = 2;</code>
     */
    public Builder clearCostThisMonth() {
      
      costThisMonth_ = 0D;
      onChanged();
      return this;
    }

    private com.google.protobuf.MapField<
        java.lang.String, com.didiyun.bill.v1.FactorRuleDetail> chargeInfo_;
    private com.google.protobuf.MapField<java.lang.String, com.didiyun.bill.v1.FactorRuleDetail>
    internalGetChargeInfo() {
      if (chargeInfo_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            ChargeInfoDefaultEntryHolder.defaultEntry);
      }
      return chargeInfo_;
    }
    private com.google.protobuf.MapField<java.lang.String, com.didiyun.bill.v1.FactorRuleDetail>
    internalGetMutableChargeInfo() {
      onChanged();;
      if (chargeInfo_ == null) {
        chargeInfo_ = com.google.protobuf.MapField.newMapField(
            ChargeInfoDefaultEntryHolder.defaultEntry);
      }
      if (!chargeInfo_.isMutable()) {
        chargeInfo_ = chargeInfo_.copy();
      }
      return chargeInfo_;
    }

    public int getChargeInfoCount() {
      return internalGetChargeInfo().getMap().size();
    }
    /**
     * <pre>
     *当前此资源的计费信息.key为计费项factor
     * </pre>
     *
     * <code>map&lt;string, .didi.cloud.bill.v1.FactorRuleDetail&gt; chargeInfo = 3;</code>
     */

    public boolean containsChargeInfo(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      return internalGetChargeInfo().getMap().containsKey(key);
    }
    /**
     * Use {@link #getChargeInfoMap()} instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, com.didiyun.bill.v1.FactorRuleDetail> getChargeInfo() {
      return getChargeInfoMap();
    }
    /**
     * <pre>
     *当前此资源的计费信息.key为计费项factor
     * </pre>
     *
     * <code>map&lt;string, .didi.cloud.bill.v1.FactorRuleDetail&gt; chargeInfo = 3;</code>
     */

    public java.util.Map<java.lang.String, com.didiyun.bill.v1.FactorRuleDetail> getChargeInfoMap() {
      return internalGetChargeInfo().getMap();
    }
    /**
     * <pre>
     *当前此资源的计费信息.key为计费项factor
     * </pre>
     *
     * <code>map&lt;string, .didi.cloud.bill.v1.FactorRuleDetail&gt; chargeInfo = 3;</code>
     */

    public com.didiyun.bill.v1.FactorRuleDetail getChargeInfoOrDefault(
        java.lang.String key,
        com.didiyun.bill.v1.FactorRuleDetail defaultValue) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, com.didiyun.bill.v1.FactorRuleDetail> map =
          internalGetChargeInfo().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <pre>
     *当前此资源的计费信息.key为计费项factor
     * </pre>
     *
     * <code>map&lt;string, .didi.cloud.bill.v1.FactorRuleDetail&gt; chargeInfo = 3;</code>
     */

    public com.didiyun.bill.v1.FactorRuleDetail getChargeInfoOrThrow(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, com.didiyun.bill.v1.FactorRuleDetail> map =
          internalGetChargeInfo().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }

    public Builder clearChargeInfo() {
      internalGetMutableChargeInfo().getMutableMap()
          .clear();
      return this;
    }
    /**
     * <pre>
     *当前此资源的计费信息.key为计费项factor
     * </pre>
     *
     * <code>map&lt;string, .didi.cloud.bill.v1.FactorRuleDetail&gt; chargeInfo = 3;</code>
     */

    public Builder removeChargeInfo(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      internalGetMutableChargeInfo().getMutableMap()
          .remove(key);
      return this;
    }
    /**
     * Use alternate mutation accessors instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, com.didiyun.bill.v1.FactorRuleDetail>
    getMutableChargeInfo() {
      return internalGetMutableChargeInfo().getMutableMap();
    }
    /**
     * <pre>
     *当前此资源的计费信息.key为计费项factor
     * </pre>
     *
     * <code>map&lt;string, .didi.cloud.bill.v1.FactorRuleDetail&gt; chargeInfo = 3;</code>
     */
    public Builder putChargeInfo(
        java.lang.String key,
        com.didiyun.bill.v1.FactorRuleDetail value) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      if (value == null) { throw new java.lang.NullPointerException(); }
      internalGetMutableChargeInfo().getMutableMap()
          .put(key, value);
      return this;
    }
    /**
     * <pre>
     *当前此资源的计费信息.key为计费项factor
     * </pre>
     *
     * <code>map&lt;string, .didi.cloud.bill.v1.FactorRuleDetail&gt; chargeInfo = 3;</code>
     */

    public Builder putAllChargeInfo(
        java.util.Map<java.lang.String, com.didiyun.bill.v1.FactorRuleDetail> values) {
      internalGetMutableChargeInfo().getMutableMap()
          .putAll(values);
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:didi.cloud.bill.v1.ChargeInfo)
  }

  // @@protoc_insertion_point(class_scope:didi.cloud.bill.v1.ChargeInfo)
  private static final com.didiyun.bill.v1.ChargeInfo DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.didiyun.bill.v1.ChargeInfo();
  }

  public static com.didiyun.bill.v1.ChargeInfo getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ChargeInfo>
      PARSER = new com.google.protobuf.AbstractParser<ChargeInfo>() {
    @java.lang.Override
    public ChargeInfo parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new ChargeInfo(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<ChargeInfo> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ChargeInfo> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.didiyun.bill.v1.ChargeInfo getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

