// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: bill/v1/bill.proto

package com.didiyun.bill.v1;

public interface CheckEipPriceInputOrBuilder extends
    // @@protoc_insertion_point(interface_extends:didi.cloud.bill.v1.CheckEipPriceInput)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   *eip数量
   * </pre>
   *
   * <code>int32 count = 1;</code>
   */
  int getCount();

  /**
   * <pre>
   *购买包月时长，单位为月，不传或传0表示后付费
   * </pre>
   *
   * <code>int32 payPeriod = 2;</code>
   */
  int getPayPeriod();

  /**
   * <pre>
   *eip带宽
   * </pre>
   *
   * <code>int32 bandwidth = 3;</code>
   */
  int getBandwidth();

  /**
   * <pre>
   *是否按流量计费
   * </pre>
   *
   * <code>bool chargeWithFlow = 4;</code>
   */
  boolean getChargeWithFlow();

  /**
   * <pre>
   *当为更改规格时，传此eipUuid
   * </pre>
   *
   * <code>string eipUuid = 5;</code>
   */
  java.lang.String getEipUuid();
  /**
   * <pre>
   *当为更改规格时，传此eipUuid
   * </pre>
   *
   * <code>string eipUuid = 5;</code>
   */
  com.google.protobuf.ByteString
      getEipUuidBytes();
}
