// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: bill/v1/bill.proto

package com.didiyun.bill.v1;

public interface ResourceItemInputOrBuilder extends
    // @@protoc_insertion_point(interface_extends:didi.cloud.bill.v1.ResourceItemInput)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   *资源uuid
   * </pre>
   *
   * <code>string resourceUuid = 1;</code>
   */
  java.lang.String getResourceUuid();
  /**
   * <pre>
   *资源uuid
   * </pre>
   *
   * <code>string resourceUuid = 1;</code>
   */
  com.google.protobuf.ByteString
      getResourceUuidBytes();

  /**
   * <pre>
   *资源类型
   * </pre>
   *
   * <code>string resourceType = 2;</code>
   */
  java.lang.String getResourceType();
  /**
   * <pre>
   *资源类型
   * </pre>
   *
   * <code>string resourceType = 2;</code>
   */
  com.google.protobuf.ByteString
      getResourceTypeBytes();
}
