// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: compute/v1/vpc.proto

package com.didiyun.compute.v1;

/**
 * Protobuf type {@code didi.cloud.compute.v1.ChangeSubnetNameRequest}
 */
public  final class ChangeSubnetNameRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:didi.cloud.compute.v1.ChangeSubnetNameRequest)
    ChangeSubnetNameRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ChangeSubnetNameRequest.newBuilder() to construct.
  private ChangeSubnetNameRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ChangeSubnetNameRequest() {
    vpcUuid_ = "";
    subnet_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private ChangeSubnetNameRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            com.didiyun.base.v1.Header.Builder subBuilder = null;
            if (header_ != null) {
              subBuilder = header_.toBuilder();
            }
            header_ = input.readMessage(com.didiyun.base.v1.Header.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(header_);
              header_ = subBuilder.buildPartial();
            }

            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            vpcUuid_ = s;
            break;
          }
          case 26: {
            if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
              subnet_ = new java.util.ArrayList<com.didiyun.compute.v1.ChangeSubnetNameRequest.Input>();
              mutable_bitField0_ |= 0x00000004;
            }
            subnet_.add(
                input.readMessage(com.didiyun.compute.v1.ChangeSubnetNameRequest.Input.parser(), extensionRegistry));
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
        subnet_ = java.util.Collections.unmodifiableList(subnet_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.didiyun.compute.v1.VpcOuterClass.internal_static_didi_cloud_compute_v1_ChangeSubnetNameRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.didiyun.compute.v1.VpcOuterClass.internal_static_didi_cloud_compute_v1_ChangeSubnetNameRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.didiyun.compute.v1.ChangeSubnetNameRequest.class, com.didiyun.compute.v1.ChangeSubnetNameRequest.Builder.class);
  }

  public interface InputOrBuilder extends
      // @@protoc_insertion_point(interface_extends:didi.cloud.compute.v1.ChangeSubnetNameRequest.Input)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *待改名的Subnet的Uuid
     * </pre>
     *
     * <code>string subnetUuid = 1;</code>
     */
    java.lang.String getSubnetUuid();
    /**
     * <pre>
     *待改名的Subnet的Uuid
     * </pre>
     *
     * <code>string subnetUuid = 1;</code>
     */
    com.google.protobuf.ByteString
        getSubnetUuidBytes();

    /**
     * <code>string name = 2;</code>
     */
    java.lang.String getName();
    /**
     * <code>string name = 2;</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();
  }
  /**
   * Protobuf type {@code didi.cloud.compute.v1.ChangeSubnetNameRequest.Input}
   */
  public  static final class Input extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:didi.cloud.compute.v1.ChangeSubnetNameRequest.Input)
      InputOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Input.newBuilder() to construct.
    private Input(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Input() {
      subnetUuid_ = "";
      name_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Input(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              subnetUuid_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              name_ = s;
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.didiyun.compute.v1.VpcOuterClass.internal_static_didi_cloud_compute_v1_ChangeSubnetNameRequest_Input_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.didiyun.compute.v1.VpcOuterClass.internal_static_didi_cloud_compute_v1_ChangeSubnetNameRequest_Input_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.didiyun.compute.v1.ChangeSubnetNameRequest.Input.class, com.didiyun.compute.v1.ChangeSubnetNameRequest.Input.Builder.class);
    }

    public static final int SUBNETUUID_FIELD_NUMBER = 1;
    private volatile java.lang.Object subnetUuid_;
    /**
     * <pre>
     *待改名的Subnet的Uuid
     * </pre>
     *
     * <code>string subnetUuid = 1;</code>
     */
    public java.lang.String getSubnetUuid() {
      java.lang.Object ref = subnetUuid_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        subnetUuid_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *待改名的Subnet的Uuid
     * </pre>
     *
     * <code>string subnetUuid = 1;</code>
     */
    public com.google.protobuf.ByteString
        getSubnetUuidBytes() {
      java.lang.Object ref = subnetUuid_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        subnetUuid_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int NAME_FIELD_NUMBER = 2;
    private volatile java.lang.Object name_;
    /**
     * <code>string name = 2;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     * <code>string name = 2;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getSubnetUuidBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, subnetUuid_);
      }
      if (!getNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, name_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getSubnetUuidBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, subnetUuid_);
      }
      if (!getNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, name_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.didiyun.compute.v1.ChangeSubnetNameRequest.Input)) {
        return super.equals(obj);
      }
      com.didiyun.compute.v1.ChangeSubnetNameRequest.Input other = (com.didiyun.compute.v1.ChangeSubnetNameRequest.Input) obj;

      boolean result = true;
      result = result && getSubnetUuid()
          .equals(other.getSubnetUuid());
      result = result && getName()
          .equals(other.getName());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + SUBNETUUID_FIELD_NUMBER;
      hash = (53 * hash) + getSubnetUuid().hashCode();
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.didiyun.compute.v1.ChangeSubnetNameRequest.Input parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.didiyun.compute.v1.ChangeSubnetNameRequest.Input parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.didiyun.compute.v1.ChangeSubnetNameRequest.Input parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.didiyun.compute.v1.ChangeSubnetNameRequest.Input parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.didiyun.compute.v1.ChangeSubnetNameRequest.Input parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.didiyun.compute.v1.ChangeSubnetNameRequest.Input parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.didiyun.compute.v1.ChangeSubnetNameRequest.Input parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.didiyun.compute.v1.ChangeSubnetNameRequest.Input parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.didiyun.compute.v1.ChangeSubnetNameRequest.Input parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.didiyun.compute.v1.ChangeSubnetNameRequest.Input parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.didiyun.compute.v1.ChangeSubnetNameRequest.Input parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.didiyun.compute.v1.ChangeSubnetNameRequest.Input parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.didiyun.compute.v1.ChangeSubnetNameRequest.Input prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code didi.cloud.compute.v1.ChangeSubnetNameRequest.Input}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:didi.cloud.compute.v1.ChangeSubnetNameRequest.Input)
        com.didiyun.compute.v1.ChangeSubnetNameRequest.InputOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.didiyun.compute.v1.VpcOuterClass.internal_static_didi_cloud_compute_v1_ChangeSubnetNameRequest_Input_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.didiyun.compute.v1.VpcOuterClass.internal_static_didi_cloud_compute_v1_ChangeSubnetNameRequest_Input_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.didiyun.compute.v1.ChangeSubnetNameRequest.Input.class, com.didiyun.compute.v1.ChangeSubnetNameRequest.Input.Builder.class);
      }

      // Construct using com.didiyun.compute.v1.ChangeSubnetNameRequest.Input.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        subnetUuid_ = "";

        name_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.didiyun.compute.v1.VpcOuterClass.internal_static_didi_cloud_compute_v1_ChangeSubnetNameRequest_Input_descriptor;
      }

      @java.lang.Override
      public com.didiyun.compute.v1.ChangeSubnetNameRequest.Input getDefaultInstanceForType() {
        return com.didiyun.compute.v1.ChangeSubnetNameRequest.Input.getDefaultInstance();
      }

      @java.lang.Override
      public com.didiyun.compute.v1.ChangeSubnetNameRequest.Input build() {
        com.didiyun.compute.v1.ChangeSubnetNameRequest.Input result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.didiyun.compute.v1.ChangeSubnetNameRequest.Input buildPartial() {
        com.didiyun.compute.v1.ChangeSubnetNameRequest.Input result = new com.didiyun.compute.v1.ChangeSubnetNameRequest.Input(this);
        result.subnetUuid_ = subnetUuid_;
        result.name_ = name_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.didiyun.compute.v1.ChangeSubnetNameRequest.Input) {
          return mergeFrom((com.didiyun.compute.v1.ChangeSubnetNameRequest.Input)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.didiyun.compute.v1.ChangeSubnetNameRequest.Input other) {
        if (other == com.didiyun.compute.v1.ChangeSubnetNameRequest.Input.getDefaultInstance()) return this;
        if (!other.getSubnetUuid().isEmpty()) {
          subnetUuid_ = other.subnetUuid_;
          onChanged();
        }
        if (!other.getName().isEmpty()) {
          name_ = other.name_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.didiyun.compute.v1.ChangeSubnetNameRequest.Input parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.didiyun.compute.v1.ChangeSubnetNameRequest.Input) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object subnetUuid_ = "";
      /**
       * <pre>
       *待改名的Subnet的Uuid
       * </pre>
       *
       * <code>string subnetUuid = 1;</code>
       */
      public java.lang.String getSubnetUuid() {
        java.lang.Object ref = subnetUuid_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          subnetUuid_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *待改名的Subnet的Uuid
       * </pre>
       *
       * <code>string subnetUuid = 1;</code>
       */
      public com.google.protobuf.ByteString
          getSubnetUuidBytes() {
        java.lang.Object ref = subnetUuid_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          subnetUuid_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *待改名的Subnet的Uuid
       * </pre>
       *
       * <code>string subnetUuid = 1;</code>
       */
      public Builder setSubnetUuid(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        subnetUuid_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *待改名的Subnet的Uuid
       * </pre>
       *
       * <code>string subnetUuid = 1;</code>
       */
      public Builder clearSubnetUuid() {
        
        subnetUuid_ = getDefaultInstance().getSubnetUuid();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *待改名的Subnet的Uuid
       * </pre>
       *
       * <code>string subnetUuid = 1;</code>
       */
      public Builder setSubnetUuidBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        subnetUuid_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object name_ = "";
      /**
       * <code>string name = 2;</code>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string name = 2;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string name = 2;</code>
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string name = 2;</code>
       */
      public Builder clearName() {
        
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>string name = 2;</code>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        name_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:didi.cloud.compute.v1.ChangeSubnetNameRequest.Input)
    }

    // @@protoc_insertion_point(class_scope:didi.cloud.compute.v1.ChangeSubnetNameRequest.Input)
    private static final com.didiyun.compute.v1.ChangeSubnetNameRequest.Input DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.didiyun.compute.v1.ChangeSubnetNameRequest.Input();
    }

    public static com.didiyun.compute.v1.ChangeSubnetNameRequest.Input getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Input>
        PARSER = new com.google.protobuf.AbstractParser<Input>() {
      @java.lang.Override
      public Input parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Input(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Input> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Input> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.didiyun.compute.v1.ChangeSubnetNameRequest.Input getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private int bitField0_;
  public static final int HEADER_FIELD_NUMBER = 1;
  private com.didiyun.base.v1.Header header_;
  /**
   * <pre>
   *公共的请求头
   * </pre>
   *
   * <code>.didi.cloud.base.v1.Header header = 1;</code>
   */
  public boolean hasHeader() {
    return header_ != null;
  }
  /**
   * <pre>
   *公共的请求头
   * </pre>
   *
   * <code>.didi.cloud.base.v1.Header header = 1;</code>
   */
  public com.didiyun.base.v1.Header getHeader() {
    return header_ == null ? com.didiyun.base.v1.Header.getDefaultInstance() : header_;
  }
  /**
   * <pre>
   *公共的请求头
   * </pre>
   *
   * <code>.didi.cloud.base.v1.Header header = 1;</code>
   */
  public com.didiyun.base.v1.HeaderOrBuilder getHeaderOrBuilder() {
    return getHeader();
  }

  public static final int VPCUUID_FIELD_NUMBER = 2;
  private volatile java.lang.Object vpcUuid_;
  /**
   * <pre>
   *待改名的Subnet所在vpc的Uuid
   * </pre>
   *
   * <code>string vpcUuid = 2;</code>
   */
  public java.lang.String getVpcUuid() {
    java.lang.Object ref = vpcUuid_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      vpcUuid_ = s;
      return s;
    }
  }
  /**
   * <pre>
   *待改名的Subnet所在vpc的Uuid
   * </pre>
   *
   * <code>string vpcUuid = 2;</code>
   */
  public com.google.protobuf.ByteString
      getVpcUuidBytes() {
    java.lang.Object ref = vpcUuid_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      vpcUuid_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SUBNET_FIELD_NUMBER = 3;
  private java.util.List<com.didiyun.compute.v1.ChangeSubnetNameRequest.Input> subnet_;
  /**
   * <code>repeated .didi.cloud.compute.v1.ChangeSubnetNameRequest.Input subnet = 3;</code>
   */
  public java.util.List<com.didiyun.compute.v1.ChangeSubnetNameRequest.Input> getSubnetList() {
    return subnet_;
  }
  /**
   * <code>repeated .didi.cloud.compute.v1.ChangeSubnetNameRequest.Input subnet = 3;</code>
   */
  public java.util.List<? extends com.didiyun.compute.v1.ChangeSubnetNameRequest.InputOrBuilder> 
      getSubnetOrBuilderList() {
    return subnet_;
  }
  /**
   * <code>repeated .didi.cloud.compute.v1.ChangeSubnetNameRequest.Input subnet = 3;</code>
   */
  public int getSubnetCount() {
    return subnet_.size();
  }
  /**
   * <code>repeated .didi.cloud.compute.v1.ChangeSubnetNameRequest.Input subnet = 3;</code>
   */
  public com.didiyun.compute.v1.ChangeSubnetNameRequest.Input getSubnet(int index) {
    return subnet_.get(index);
  }
  /**
   * <code>repeated .didi.cloud.compute.v1.ChangeSubnetNameRequest.Input subnet = 3;</code>
   */
  public com.didiyun.compute.v1.ChangeSubnetNameRequest.InputOrBuilder getSubnetOrBuilder(
      int index) {
    return subnet_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (header_ != null) {
      output.writeMessage(1, getHeader());
    }
    if (!getVpcUuidBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, vpcUuid_);
    }
    for (int i = 0; i < subnet_.size(); i++) {
      output.writeMessage(3, subnet_.get(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (header_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getHeader());
    }
    if (!getVpcUuidBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, vpcUuid_);
    }
    for (int i = 0; i < subnet_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, subnet_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.didiyun.compute.v1.ChangeSubnetNameRequest)) {
      return super.equals(obj);
    }
    com.didiyun.compute.v1.ChangeSubnetNameRequest other = (com.didiyun.compute.v1.ChangeSubnetNameRequest) obj;

    boolean result = true;
    result = result && (hasHeader() == other.hasHeader());
    if (hasHeader()) {
      result = result && getHeader()
          .equals(other.getHeader());
    }
    result = result && getVpcUuid()
        .equals(other.getVpcUuid());
    result = result && getSubnetList()
        .equals(other.getSubnetList());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasHeader()) {
      hash = (37 * hash) + HEADER_FIELD_NUMBER;
      hash = (53 * hash) + getHeader().hashCode();
    }
    hash = (37 * hash) + VPCUUID_FIELD_NUMBER;
    hash = (53 * hash) + getVpcUuid().hashCode();
    if (getSubnetCount() > 0) {
      hash = (37 * hash) + SUBNET_FIELD_NUMBER;
      hash = (53 * hash) + getSubnetList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.didiyun.compute.v1.ChangeSubnetNameRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.didiyun.compute.v1.ChangeSubnetNameRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.didiyun.compute.v1.ChangeSubnetNameRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.didiyun.compute.v1.ChangeSubnetNameRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.didiyun.compute.v1.ChangeSubnetNameRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.didiyun.compute.v1.ChangeSubnetNameRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.didiyun.compute.v1.ChangeSubnetNameRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.didiyun.compute.v1.ChangeSubnetNameRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.didiyun.compute.v1.ChangeSubnetNameRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.didiyun.compute.v1.ChangeSubnetNameRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.didiyun.compute.v1.ChangeSubnetNameRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.didiyun.compute.v1.ChangeSubnetNameRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.didiyun.compute.v1.ChangeSubnetNameRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code didi.cloud.compute.v1.ChangeSubnetNameRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:didi.cloud.compute.v1.ChangeSubnetNameRequest)
      com.didiyun.compute.v1.ChangeSubnetNameRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.didiyun.compute.v1.VpcOuterClass.internal_static_didi_cloud_compute_v1_ChangeSubnetNameRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.didiyun.compute.v1.VpcOuterClass.internal_static_didi_cloud_compute_v1_ChangeSubnetNameRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.didiyun.compute.v1.ChangeSubnetNameRequest.class, com.didiyun.compute.v1.ChangeSubnetNameRequest.Builder.class);
    }

    // Construct using com.didiyun.compute.v1.ChangeSubnetNameRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getSubnetFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (headerBuilder_ == null) {
        header_ = null;
      } else {
        header_ = null;
        headerBuilder_ = null;
      }
      vpcUuid_ = "";

      if (subnetBuilder_ == null) {
        subnet_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000004);
      } else {
        subnetBuilder_.clear();
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.didiyun.compute.v1.VpcOuterClass.internal_static_didi_cloud_compute_v1_ChangeSubnetNameRequest_descriptor;
    }

    @java.lang.Override
    public com.didiyun.compute.v1.ChangeSubnetNameRequest getDefaultInstanceForType() {
      return com.didiyun.compute.v1.ChangeSubnetNameRequest.getDefaultInstance();
    }

    @java.lang.Override
    public com.didiyun.compute.v1.ChangeSubnetNameRequest build() {
      com.didiyun.compute.v1.ChangeSubnetNameRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.didiyun.compute.v1.ChangeSubnetNameRequest buildPartial() {
      com.didiyun.compute.v1.ChangeSubnetNameRequest result = new com.didiyun.compute.v1.ChangeSubnetNameRequest(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (headerBuilder_ == null) {
        result.header_ = header_;
      } else {
        result.header_ = headerBuilder_.build();
      }
      result.vpcUuid_ = vpcUuid_;
      if (subnetBuilder_ == null) {
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          subnet_ = java.util.Collections.unmodifiableList(subnet_);
          bitField0_ = (bitField0_ & ~0x00000004);
        }
        result.subnet_ = subnet_;
      } else {
        result.subnet_ = subnetBuilder_.build();
      }
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.didiyun.compute.v1.ChangeSubnetNameRequest) {
        return mergeFrom((com.didiyun.compute.v1.ChangeSubnetNameRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.didiyun.compute.v1.ChangeSubnetNameRequest other) {
      if (other == com.didiyun.compute.v1.ChangeSubnetNameRequest.getDefaultInstance()) return this;
      if (other.hasHeader()) {
        mergeHeader(other.getHeader());
      }
      if (!other.getVpcUuid().isEmpty()) {
        vpcUuid_ = other.vpcUuid_;
        onChanged();
      }
      if (subnetBuilder_ == null) {
        if (!other.subnet_.isEmpty()) {
          if (subnet_.isEmpty()) {
            subnet_ = other.subnet_;
            bitField0_ = (bitField0_ & ~0x00000004);
          } else {
            ensureSubnetIsMutable();
            subnet_.addAll(other.subnet_);
          }
          onChanged();
        }
      } else {
        if (!other.subnet_.isEmpty()) {
          if (subnetBuilder_.isEmpty()) {
            subnetBuilder_.dispose();
            subnetBuilder_ = null;
            subnet_ = other.subnet_;
            bitField0_ = (bitField0_ & ~0x00000004);
            subnetBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getSubnetFieldBuilder() : null;
          } else {
            subnetBuilder_.addAllMessages(other.subnet_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.didiyun.compute.v1.ChangeSubnetNameRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.didiyun.compute.v1.ChangeSubnetNameRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private com.didiyun.base.v1.Header header_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.didiyun.base.v1.Header, com.didiyun.base.v1.Header.Builder, com.didiyun.base.v1.HeaderOrBuilder> headerBuilder_;
    /**
     * <pre>
     *公共的请求头
     * </pre>
     *
     * <code>.didi.cloud.base.v1.Header header = 1;</code>
     */
    public boolean hasHeader() {
      return headerBuilder_ != null || header_ != null;
    }
    /**
     * <pre>
     *公共的请求头
     * </pre>
     *
     * <code>.didi.cloud.base.v1.Header header = 1;</code>
     */
    public com.didiyun.base.v1.Header getHeader() {
      if (headerBuilder_ == null) {
        return header_ == null ? com.didiyun.base.v1.Header.getDefaultInstance() : header_;
      } else {
        return headerBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     *公共的请求头
     * </pre>
     *
     * <code>.didi.cloud.base.v1.Header header = 1;</code>
     */
    public Builder setHeader(com.didiyun.base.v1.Header value) {
      if (headerBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        header_ = value;
        onChanged();
      } else {
        headerBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <pre>
     *公共的请求头
     * </pre>
     *
     * <code>.didi.cloud.base.v1.Header header = 1;</code>
     */
    public Builder setHeader(
        com.didiyun.base.v1.Header.Builder builderForValue) {
      if (headerBuilder_ == null) {
        header_ = builderForValue.build();
        onChanged();
      } else {
        headerBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <pre>
     *公共的请求头
     * </pre>
     *
     * <code>.didi.cloud.base.v1.Header header = 1;</code>
     */
    public Builder mergeHeader(com.didiyun.base.v1.Header value) {
      if (headerBuilder_ == null) {
        if (header_ != null) {
          header_ =
            com.didiyun.base.v1.Header.newBuilder(header_).mergeFrom(value).buildPartial();
        } else {
          header_ = value;
        }
        onChanged();
      } else {
        headerBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <pre>
     *公共的请求头
     * </pre>
     *
     * <code>.didi.cloud.base.v1.Header header = 1;</code>
     */
    public Builder clearHeader() {
      if (headerBuilder_ == null) {
        header_ = null;
        onChanged();
      } else {
        header_ = null;
        headerBuilder_ = null;
      }

      return this;
    }
    /**
     * <pre>
     *公共的请求头
     * </pre>
     *
     * <code>.didi.cloud.base.v1.Header header = 1;</code>
     */
    public com.didiyun.base.v1.Header.Builder getHeaderBuilder() {
      
      onChanged();
      return getHeaderFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     *公共的请求头
     * </pre>
     *
     * <code>.didi.cloud.base.v1.Header header = 1;</code>
     */
    public com.didiyun.base.v1.HeaderOrBuilder getHeaderOrBuilder() {
      if (headerBuilder_ != null) {
        return headerBuilder_.getMessageOrBuilder();
      } else {
        return header_ == null ?
            com.didiyun.base.v1.Header.getDefaultInstance() : header_;
      }
    }
    /**
     * <pre>
     *公共的请求头
     * </pre>
     *
     * <code>.didi.cloud.base.v1.Header header = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.didiyun.base.v1.Header, com.didiyun.base.v1.Header.Builder, com.didiyun.base.v1.HeaderOrBuilder> 
        getHeaderFieldBuilder() {
      if (headerBuilder_ == null) {
        headerBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.didiyun.base.v1.Header, com.didiyun.base.v1.Header.Builder, com.didiyun.base.v1.HeaderOrBuilder>(
                getHeader(),
                getParentForChildren(),
                isClean());
        header_ = null;
      }
      return headerBuilder_;
    }

    private java.lang.Object vpcUuid_ = "";
    /**
     * <pre>
     *待改名的Subnet所在vpc的Uuid
     * </pre>
     *
     * <code>string vpcUuid = 2;</code>
     */
    public java.lang.String getVpcUuid() {
      java.lang.Object ref = vpcUuid_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        vpcUuid_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     *待改名的Subnet所在vpc的Uuid
     * </pre>
     *
     * <code>string vpcUuid = 2;</code>
     */
    public com.google.protobuf.ByteString
        getVpcUuidBytes() {
      java.lang.Object ref = vpcUuid_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        vpcUuid_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     *待改名的Subnet所在vpc的Uuid
     * </pre>
     *
     * <code>string vpcUuid = 2;</code>
     */
    public Builder setVpcUuid(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      vpcUuid_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *待改名的Subnet所在vpc的Uuid
     * </pre>
     *
     * <code>string vpcUuid = 2;</code>
     */
    public Builder clearVpcUuid() {
      
      vpcUuid_ = getDefaultInstance().getVpcUuid();
      onChanged();
      return this;
    }
    /**
     * <pre>
     *待改名的Subnet所在vpc的Uuid
     * </pre>
     *
     * <code>string vpcUuid = 2;</code>
     */
    public Builder setVpcUuidBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      vpcUuid_ = value;
      onChanged();
      return this;
    }

    private java.util.List<com.didiyun.compute.v1.ChangeSubnetNameRequest.Input> subnet_ =
      java.util.Collections.emptyList();
    private void ensureSubnetIsMutable() {
      if (!((bitField0_ & 0x00000004) == 0x00000004)) {
        subnet_ = new java.util.ArrayList<com.didiyun.compute.v1.ChangeSubnetNameRequest.Input>(subnet_);
        bitField0_ |= 0x00000004;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.didiyun.compute.v1.ChangeSubnetNameRequest.Input, com.didiyun.compute.v1.ChangeSubnetNameRequest.Input.Builder, com.didiyun.compute.v1.ChangeSubnetNameRequest.InputOrBuilder> subnetBuilder_;

    /**
     * <code>repeated .didi.cloud.compute.v1.ChangeSubnetNameRequest.Input subnet = 3;</code>
     */
    public java.util.List<com.didiyun.compute.v1.ChangeSubnetNameRequest.Input> getSubnetList() {
      if (subnetBuilder_ == null) {
        return java.util.Collections.unmodifiableList(subnet_);
      } else {
        return subnetBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .didi.cloud.compute.v1.ChangeSubnetNameRequest.Input subnet = 3;</code>
     */
    public int getSubnetCount() {
      if (subnetBuilder_ == null) {
        return subnet_.size();
      } else {
        return subnetBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .didi.cloud.compute.v1.ChangeSubnetNameRequest.Input subnet = 3;</code>
     */
    public com.didiyun.compute.v1.ChangeSubnetNameRequest.Input getSubnet(int index) {
      if (subnetBuilder_ == null) {
        return subnet_.get(index);
      } else {
        return subnetBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .didi.cloud.compute.v1.ChangeSubnetNameRequest.Input subnet = 3;</code>
     */
    public Builder setSubnet(
        int index, com.didiyun.compute.v1.ChangeSubnetNameRequest.Input value) {
      if (subnetBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureSubnetIsMutable();
        subnet_.set(index, value);
        onChanged();
      } else {
        subnetBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .didi.cloud.compute.v1.ChangeSubnetNameRequest.Input subnet = 3;</code>
     */
    public Builder setSubnet(
        int index, com.didiyun.compute.v1.ChangeSubnetNameRequest.Input.Builder builderForValue) {
      if (subnetBuilder_ == null) {
        ensureSubnetIsMutable();
        subnet_.set(index, builderForValue.build());
        onChanged();
      } else {
        subnetBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .didi.cloud.compute.v1.ChangeSubnetNameRequest.Input subnet = 3;</code>
     */
    public Builder addSubnet(com.didiyun.compute.v1.ChangeSubnetNameRequest.Input value) {
      if (subnetBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureSubnetIsMutable();
        subnet_.add(value);
        onChanged();
      } else {
        subnetBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .didi.cloud.compute.v1.ChangeSubnetNameRequest.Input subnet = 3;</code>
     */
    public Builder addSubnet(
        int index, com.didiyun.compute.v1.ChangeSubnetNameRequest.Input value) {
      if (subnetBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureSubnetIsMutable();
        subnet_.add(index, value);
        onChanged();
      } else {
        subnetBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .didi.cloud.compute.v1.ChangeSubnetNameRequest.Input subnet = 3;</code>
     */
    public Builder addSubnet(
        com.didiyun.compute.v1.ChangeSubnetNameRequest.Input.Builder builderForValue) {
      if (subnetBuilder_ == null) {
        ensureSubnetIsMutable();
        subnet_.add(builderForValue.build());
        onChanged();
      } else {
        subnetBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .didi.cloud.compute.v1.ChangeSubnetNameRequest.Input subnet = 3;</code>
     */
    public Builder addSubnet(
        int index, com.didiyun.compute.v1.ChangeSubnetNameRequest.Input.Builder builderForValue) {
      if (subnetBuilder_ == null) {
        ensureSubnetIsMutable();
        subnet_.add(index, builderForValue.build());
        onChanged();
      } else {
        subnetBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .didi.cloud.compute.v1.ChangeSubnetNameRequest.Input subnet = 3;</code>
     */
    public Builder addAllSubnet(
        java.lang.Iterable<? extends com.didiyun.compute.v1.ChangeSubnetNameRequest.Input> values) {
      if (subnetBuilder_ == null) {
        ensureSubnetIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, subnet_);
        onChanged();
      } else {
        subnetBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .didi.cloud.compute.v1.ChangeSubnetNameRequest.Input subnet = 3;</code>
     */
    public Builder clearSubnet() {
      if (subnetBuilder_ == null) {
        subnet_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
      } else {
        subnetBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .didi.cloud.compute.v1.ChangeSubnetNameRequest.Input subnet = 3;</code>
     */
    public Builder removeSubnet(int index) {
      if (subnetBuilder_ == null) {
        ensureSubnetIsMutable();
        subnet_.remove(index);
        onChanged();
      } else {
        subnetBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .didi.cloud.compute.v1.ChangeSubnetNameRequest.Input subnet = 3;</code>
     */
    public com.didiyun.compute.v1.ChangeSubnetNameRequest.Input.Builder getSubnetBuilder(
        int index) {
      return getSubnetFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .didi.cloud.compute.v1.ChangeSubnetNameRequest.Input subnet = 3;</code>
     */
    public com.didiyun.compute.v1.ChangeSubnetNameRequest.InputOrBuilder getSubnetOrBuilder(
        int index) {
      if (subnetBuilder_ == null) {
        return subnet_.get(index);  } else {
        return subnetBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .didi.cloud.compute.v1.ChangeSubnetNameRequest.Input subnet = 3;</code>
     */
    public java.util.List<? extends com.didiyun.compute.v1.ChangeSubnetNameRequest.InputOrBuilder> 
         getSubnetOrBuilderList() {
      if (subnetBuilder_ != null) {
        return subnetBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(subnet_);
      }
    }
    /**
     * <code>repeated .didi.cloud.compute.v1.ChangeSubnetNameRequest.Input subnet = 3;</code>
     */
    public com.didiyun.compute.v1.ChangeSubnetNameRequest.Input.Builder addSubnetBuilder() {
      return getSubnetFieldBuilder().addBuilder(
          com.didiyun.compute.v1.ChangeSubnetNameRequest.Input.getDefaultInstance());
    }
    /**
     * <code>repeated .didi.cloud.compute.v1.ChangeSubnetNameRequest.Input subnet = 3;</code>
     */
    public com.didiyun.compute.v1.ChangeSubnetNameRequest.Input.Builder addSubnetBuilder(
        int index) {
      return getSubnetFieldBuilder().addBuilder(
          index, com.didiyun.compute.v1.ChangeSubnetNameRequest.Input.getDefaultInstance());
    }
    /**
     * <code>repeated .didi.cloud.compute.v1.ChangeSubnetNameRequest.Input subnet = 3;</code>
     */
    public java.util.List<com.didiyun.compute.v1.ChangeSubnetNameRequest.Input.Builder> 
         getSubnetBuilderList() {
      return getSubnetFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.didiyun.compute.v1.ChangeSubnetNameRequest.Input, com.didiyun.compute.v1.ChangeSubnetNameRequest.Input.Builder, com.didiyun.compute.v1.ChangeSubnetNameRequest.InputOrBuilder> 
        getSubnetFieldBuilder() {
      if (subnetBuilder_ == null) {
        subnetBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.didiyun.compute.v1.ChangeSubnetNameRequest.Input, com.didiyun.compute.v1.ChangeSubnetNameRequest.Input.Builder, com.didiyun.compute.v1.ChangeSubnetNameRequest.InputOrBuilder>(
                subnet_,
                ((bitField0_ & 0x00000004) == 0x00000004),
                getParentForChildren(),
                isClean());
        subnet_ = null;
      }
      return subnetBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:didi.cloud.compute.v1.ChangeSubnetNameRequest)
  }

  // @@protoc_insertion_point(class_scope:didi.cloud.compute.v1.ChangeSubnetNameRequest)
  private static final com.didiyun.compute.v1.ChangeSubnetNameRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.didiyun.compute.v1.ChangeSubnetNameRequest();
  }

  public static com.didiyun.compute.v1.ChangeSubnetNameRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ChangeSubnetNameRequest>
      PARSER = new com.google.protobuf.AbstractParser<ChangeSubnetNameRequest>() {
    @java.lang.Override
    public ChangeSubnetNameRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new ChangeSubnetNameRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<ChangeSubnetNameRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ChangeSubnetNameRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.didiyun.compute.v1.ChangeSubnetNameRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

