// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: compute/v1/sg.proto

package com.didiyun.compute.v1;

/**
 * Protobuf type {@code didi.cloud.compute.v1.CreateSgRequest}
 */
public  final class CreateSgRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:didi.cloud.compute.v1.CreateSgRequest)
    CreateSgRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use CreateSgRequest.newBuilder() to construct.
  private CreateSgRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private CreateSgRequest() {
    name_ = "";
    vpcUuid_ = "";
    sgRule_ = java.util.Collections.emptyList();
    dc2_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private CreateSgRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            com.didiyun.base.v1.Header.Builder subBuilder = null;
            if (header_ != null) {
              subBuilder = header_.toBuilder();
            }
            header_ = input.readMessage(com.didiyun.base.v1.Header.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(header_);
              header_ = subBuilder.buildPartial();
            }

            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            name_ = s;
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            vpcUuid_ = s;
            break;
          }
          case 34: {
            if (!((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
              sgRule_ = new java.util.ArrayList<com.didiyun.compute.v1.CreateSgRuleInput>();
              mutable_bitField0_ |= 0x00000008;
            }
            sgRule_.add(
                input.readMessage(com.didiyun.compute.v1.CreateSgRuleInput.parser(), extensionRegistry));
            break;
          }
          case 42: {
            if (!((mutable_bitField0_ & 0x00000010) == 0x00000010)) {
              dc2_ = new java.util.ArrayList<com.didiyun.compute.v1.CreateSgRequest.DC2>();
              mutable_bitField0_ |= 0x00000010;
            }
            dc2_.add(
                input.readMessage(com.didiyun.compute.v1.CreateSgRequest.DC2.parser(), extensionRegistry));
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
        sgRule_ = java.util.Collections.unmodifiableList(sgRule_);
      }
      if (((mutable_bitField0_ & 0x00000010) == 0x00000010)) {
        dc2_ = java.util.Collections.unmodifiableList(dc2_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.didiyun.compute.v1.SgOuterClass.internal_static_didi_cloud_compute_v1_CreateSgRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.didiyun.compute.v1.SgOuterClass.internal_static_didi_cloud_compute_v1_CreateSgRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.didiyun.compute.v1.CreateSgRequest.class, com.didiyun.compute.v1.CreateSgRequest.Builder.class);
  }

  public interface DC2OrBuilder extends
      // @@protoc_insertion_point(interface_extends:didi.cloud.compute.v1.CreateSgRequest.DC2)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *要绑定此Sg的Dc2的Uuid
     * </pre>
     *
     * <code>string dc2Uuid = 1;</code>
     */
    java.lang.String getDc2Uuid();
    /**
     * <pre>
     *要绑定此Sg的Dc2的Uuid
     * </pre>
     *
     * <code>string dc2Uuid = 1;</code>
     */
    com.google.protobuf.ByteString
        getDc2UuidBytes();
  }
  /**
   * Protobuf type {@code didi.cloud.compute.v1.CreateSgRequest.DC2}
   */
  public  static final class DC2 extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:didi.cloud.compute.v1.CreateSgRequest.DC2)
      DC2OrBuilder {
  private static final long serialVersionUID = 0L;
    // Use DC2.newBuilder() to construct.
    private DC2(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private DC2() {
      dc2Uuid_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private DC2(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              dc2Uuid_ = s;
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.didiyun.compute.v1.SgOuterClass.internal_static_didi_cloud_compute_v1_CreateSgRequest_DC2_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.didiyun.compute.v1.SgOuterClass.internal_static_didi_cloud_compute_v1_CreateSgRequest_DC2_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.didiyun.compute.v1.CreateSgRequest.DC2.class, com.didiyun.compute.v1.CreateSgRequest.DC2.Builder.class);
    }

    public static final int DC2UUID_FIELD_NUMBER = 1;
    private volatile java.lang.Object dc2Uuid_;
    /**
     * <pre>
     *要绑定此Sg的Dc2的Uuid
     * </pre>
     *
     * <code>string dc2Uuid = 1;</code>
     */
    public java.lang.String getDc2Uuid() {
      java.lang.Object ref = dc2Uuid_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        dc2Uuid_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *要绑定此Sg的Dc2的Uuid
     * </pre>
     *
     * <code>string dc2Uuid = 1;</code>
     */
    public com.google.protobuf.ByteString
        getDc2UuidBytes() {
      java.lang.Object ref = dc2Uuid_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        dc2Uuid_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getDc2UuidBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, dc2Uuid_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getDc2UuidBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, dc2Uuid_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.didiyun.compute.v1.CreateSgRequest.DC2)) {
        return super.equals(obj);
      }
      com.didiyun.compute.v1.CreateSgRequest.DC2 other = (com.didiyun.compute.v1.CreateSgRequest.DC2) obj;

      boolean result = true;
      result = result && getDc2Uuid()
          .equals(other.getDc2Uuid());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + DC2UUID_FIELD_NUMBER;
      hash = (53 * hash) + getDc2Uuid().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.didiyun.compute.v1.CreateSgRequest.DC2 parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.didiyun.compute.v1.CreateSgRequest.DC2 parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.didiyun.compute.v1.CreateSgRequest.DC2 parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.didiyun.compute.v1.CreateSgRequest.DC2 parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.didiyun.compute.v1.CreateSgRequest.DC2 parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.didiyun.compute.v1.CreateSgRequest.DC2 parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.didiyun.compute.v1.CreateSgRequest.DC2 parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.didiyun.compute.v1.CreateSgRequest.DC2 parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.didiyun.compute.v1.CreateSgRequest.DC2 parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.didiyun.compute.v1.CreateSgRequest.DC2 parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.didiyun.compute.v1.CreateSgRequest.DC2 parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.didiyun.compute.v1.CreateSgRequest.DC2 parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.didiyun.compute.v1.CreateSgRequest.DC2 prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code didi.cloud.compute.v1.CreateSgRequest.DC2}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:didi.cloud.compute.v1.CreateSgRequest.DC2)
        com.didiyun.compute.v1.CreateSgRequest.DC2OrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.didiyun.compute.v1.SgOuterClass.internal_static_didi_cloud_compute_v1_CreateSgRequest_DC2_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.didiyun.compute.v1.SgOuterClass.internal_static_didi_cloud_compute_v1_CreateSgRequest_DC2_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.didiyun.compute.v1.CreateSgRequest.DC2.class, com.didiyun.compute.v1.CreateSgRequest.DC2.Builder.class);
      }

      // Construct using com.didiyun.compute.v1.CreateSgRequest.DC2.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        dc2Uuid_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.didiyun.compute.v1.SgOuterClass.internal_static_didi_cloud_compute_v1_CreateSgRequest_DC2_descriptor;
      }

      @java.lang.Override
      public com.didiyun.compute.v1.CreateSgRequest.DC2 getDefaultInstanceForType() {
        return com.didiyun.compute.v1.CreateSgRequest.DC2.getDefaultInstance();
      }

      @java.lang.Override
      public com.didiyun.compute.v1.CreateSgRequest.DC2 build() {
        com.didiyun.compute.v1.CreateSgRequest.DC2 result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.didiyun.compute.v1.CreateSgRequest.DC2 buildPartial() {
        com.didiyun.compute.v1.CreateSgRequest.DC2 result = new com.didiyun.compute.v1.CreateSgRequest.DC2(this);
        result.dc2Uuid_ = dc2Uuid_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.didiyun.compute.v1.CreateSgRequest.DC2) {
          return mergeFrom((com.didiyun.compute.v1.CreateSgRequest.DC2)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.didiyun.compute.v1.CreateSgRequest.DC2 other) {
        if (other == com.didiyun.compute.v1.CreateSgRequest.DC2.getDefaultInstance()) return this;
        if (!other.getDc2Uuid().isEmpty()) {
          dc2Uuid_ = other.dc2Uuid_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.didiyun.compute.v1.CreateSgRequest.DC2 parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.didiyun.compute.v1.CreateSgRequest.DC2) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object dc2Uuid_ = "";
      /**
       * <pre>
       *要绑定此Sg的Dc2的Uuid
       * </pre>
       *
       * <code>string dc2Uuid = 1;</code>
       */
      public java.lang.String getDc2Uuid() {
        java.lang.Object ref = dc2Uuid_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          dc2Uuid_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *要绑定此Sg的Dc2的Uuid
       * </pre>
       *
       * <code>string dc2Uuid = 1;</code>
       */
      public com.google.protobuf.ByteString
          getDc2UuidBytes() {
        java.lang.Object ref = dc2Uuid_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          dc2Uuid_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *要绑定此Sg的Dc2的Uuid
       * </pre>
       *
       * <code>string dc2Uuid = 1;</code>
       */
      public Builder setDc2Uuid(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        dc2Uuid_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *要绑定此Sg的Dc2的Uuid
       * </pre>
       *
       * <code>string dc2Uuid = 1;</code>
       */
      public Builder clearDc2Uuid() {
        
        dc2Uuid_ = getDefaultInstance().getDc2Uuid();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *要绑定此Sg的Dc2的Uuid
       * </pre>
       *
       * <code>string dc2Uuid = 1;</code>
       */
      public Builder setDc2UuidBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        dc2Uuid_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:didi.cloud.compute.v1.CreateSgRequest.DC2)
    }

    // @@protoc_insertion_point(class_scope:didi.cloud.compute.v1.CreateSgRequest.DC2)
    private static final com.didiyun.compute.v1.CreateSgRequest.DC2 DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.didiyun.compute.v1.CreateSgRequest.DC2();
    }

    public static com.didiyun.compute.v1.CreateSgRequest.DC2 getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<DC2>
        PARSER = new com.google.protobuf.AbstractParser<DC2>() {
      @java.lang.Override
      public DC2 parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new DC2(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<DC2> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<DC2> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.didiyun.compute.v1.CreateSgRequest.DC2 getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private int bitField0_;
  public static final int HEADER_FIELD_NUMBER = 1;
  private com.didiyun.base.v1.Header header_;
  /**
   * <pre>
   *公共的请求头
   * </pre>
   *
   * <code>.didi.cloud.base.v1.Header header = 1;</code>
   */
  public boolean hasHeader() {
    return header_ != null;
  }
  /**
   * <pre>
   *公共的请求头
   * </pre>
   *
   * <code>.didi.cloud.base.v1.Header header = 1;</code>
   */
  public com.didiyun.base.v1.Header getHeader() {
    return header_ == null ? com.didiyun.base.v1.Header.getDefaultInstance() : header_;
  }
  /**
   * <pre>
   *公共的请求头
   * </pre>
   *
   * <code>.didi.cloud.base.v1.Header header = 1;</code>
   */
  public com.didiyun.base.v1.HeaderOrBuilder getHeaderOrBuilder() {
    return getHeader();
  }

  public static final int NAME_FIELD_NUMBER = 2;
  private volatile java.lang.Object name_;
  /**
   * <pre>
   *SG名称
   * </pre>
   *
   * <code>string name = 2;</code>
   */
  public java.lang.String getName() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      name_ = s;
      return s;
    }
  }
  /**
   * <pre>
   *SG名称
   * </pre>
   *
   * <code>string name = 2;</code>
   */
  public com.google.protobuf.ByteString
      getNameBytes() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      name_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int VPCUUID_FIELD_NUMBER = 3;
  private volatile java.lang.Object vpcUuid_;
  /**
   * <pre>
   *此SG要创建的VPC的uuid，不传则创建在指定region的默认VPC下
   * </pre>
   *
   * <code>string vpcUuid = 3;</code>
   */
  public java.lang.String getVpcUuid() {
    java.lang.Object ref = vpcUuid_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      vpcUuid_ = s;
      return s;
    }
  }
  /**
   * <pre>
   *此SG要创建的VPC的uuid，不传则创建在指定region的默认VPC下
   * </pre>
   *
   * <code>string vpcUuid = 3;</code>
   */
  public com.google.protobuf.ByteString
      getVpcUuidBytes() {
    java.lang.Object ref = vpcUuid_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      vpcUuid_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SGRULE_FIELD_NUMBER = 4;
  private java.util.List<com.didiyun.compute.v1.CreateSgRuleInput> sgRule_;
  /**
   * <pre>
   *同时在此SG下创建的规则信息
   * </pre>
   *
   * <code>repeated .didi.cloud.compute.v1.CreateSgRuleInput sgRule = 4;</code>
   */
  public java.util.List<com.didiyun.compute.v1.CreateSgRuleInput> getSgRuleList() {
    return sgRule_;
  }
  /**
   * <pre>
   *同时在此SG下创建的规则信息
   * </pre>
   *
   * <code>repeated .didi.cloud.compute.v1.CreateSgRuleInput sgRule = 4;</code>
   */
  public java.util.List<? extends com.didiyun.compute.v1.CreateSgRuleInputOrBuilder> 
      getSgRuleOrBuilderList() {
    return sgRule_;
  }
  /**
   * <pre>
   *同时在此SG下创建的规则信息
   * </pre>
   *
   * <code>repeated .didi.cloud.compute.v1.CreateSgRuleInput sgRule = 4;</code>
   */
  public int getSgRuleCount() {
    return sgRule_.size();
  }
  /**
   * <pre>
   *同时在此SG下创建的规则信息
   * </pre>
   *
   * <code>repeated .didi.cloud.compute.v1.CreateSgRuleInput sgRule = 4;</code>
   */
  public com.didiyun.compute.v1.CreateSgRuleInput getSgRule(int index) {
    return sgRule_.get(index);
  }
  /**
   * <pre>
   *同时在此SG下创建的规则信息
   * </pre>
   *
   * <code>repeated .didi.cloud.compute.v1.CreateSgRuleInput sgRule = 4;</code>
   */
  public com.didiyun.compute.v1.CreateSgRuleInputOrBuilder getSgRuleOrBuilder(
      int index) {
    return sgRule_.get(index);
  }

  public static final int DC2_FIELD_NUMBER = 5;
  private java.util.List<com.didiyun.compute.v1.CreateSgRequest.DC2> dc2_;
  /**
   * <pre>
   *需要同时添加至此SG的DC2信息
   * </pre>
   *
   * <code>repeated .didi.cloud.compute.v1.CreateSgRequest.DC2 dc2 = 5;</code>
   */
  public java.util.List<com.didiyun.compute.v1.CreateSgRequest.DC2> getDc2List() {
    return dc2_;
  }
  /**
   * <pre>
   *需要同时添加至此SG的DC2信息
   * </pre>
   *
   * <code>repeated .didi.cloud.compute.v1.CreateSgRequest.DC2 dc2 = 5;</code>
   */
  public java.util.List<? extends com.didiyun.compute.v1.CreateSgRequest.DC2OrBuilder> 
      getDc2OrBuilderList() {
    return dc2_;
  }
  /**
   * <pre>
   *需要同时添加至此SG的DC2信息
   * </pre>
   *
   * <code>repeated .didi.cloud.compute.v1.CreateSgRequest.DC2 dc2 = 5;</code>
   */
  public int getDc2Count() {
    return dc2_.size();
  }
  /**
   * <pre>
   *需要同时添加至此SG的DC2信息
   * </pre>
   *
   * <code>repeated .didi.cloud.compute.v1.CreateSgRequest.DC2 dc2 = 5;</code>
   */
  public com.didiyun.compute.v1.CreateSgRequest.DC2 getDc2(int index) {
    return dc2_.get(index);
  }
  /**
   * <pre>
   *需要同时添加至此SG的DC2信息
   * </pre>
   *
   * <code>repeated .didi.cloud.compute.v1.CreateSgRequest.DC2 dc2 = 5;</code>
   */
  public com.didiyun.compute.v1.CreateSgRequest.DC2OrBuilder getDc2OrBuilder(
      int index) {
    return dc2_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (header_ != null) {
      output.writeMessage(1, getHeader());
    }
    if (!getNameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, name_);
    }
    if (!getVpcUuidBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, vpcUuid_);
    }
    for (int i = 0; i < sgRule_.size(); i++) {
      output.writeMessage(4, sgRule_.get(i));
    }
    for (int i = 0; i < dc2_.size(); i++) {
      output.writeMessage(5, dc2_.get(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (header_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getHeader());
    }
    if (!getNameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, name_);
    }
    if (!getVpcUuidBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, vpcUuid_);
    }
    for (int i = 0; i < sgRule_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, sgRule_.get(i));
    }
    for (int i = 0; i < dc2_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(5, dc2_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.didiyun.compute.v1.CreateSgRequest)) {
      return super.equals(obj);
    }
    com.didiyun.compute.v1.CreateSgRequest other = (com.didiyun.compute.v1.CreateSgRequest) obj;

    boolean result = true;
    result = result && (hasHeader() == other.hasHeader());
    if (hasHeader()) {
      result = result && getHeader()
          .equals(other.getHeader());
    }
    result = result && getName()
        .equals(other.getName());
    result = result && getVpcUuid()
        .equals(other.getVpcUuid());
    result = result && getSgRuleList()
        .equals(other.getSgRuleList());
    result = result && getDc2List()
        .equals(other.getDc2List());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasHeader()) {
      hash = (37 * hash) + HEADER_FIELD_NUMBER;
      hash = (53 * hash) + getHeader().hashCode();
    }
    hash = (37 * hash) + NAME_FIELD_NUMBER;
    hash = (53 * hash) + getName().hashCode();
    hash = (37 * hash) + VPCUUID_FIELD_NUMBER;
    hash = (53 * hash) + getVpcUuid().hashCode();
    if (getSgRuleCount() > 0) {
      hash = (37 * hash) + SGRULE_FIELD_NUMBER;
      hash = (53 * hash) + getSgRuleList().hashCode();
    }
    if (getDc2Count() > 0) {
      hash = (37 * hash) + DC2_FIELD_NUMBER;
      hash = (53 * hash) + getDc2List().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.didiyun.compute.v1.CreateSgRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.didiyun.compute.v1.CreateSgRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.didiyun.compute.v1.CreateSgRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.didiyun.compute.v1.CreateSgRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.didiyun.compute.v1.CreateSgRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.didiyun.compute.v1.CreateSgRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.didiyun.compute.v1.CreateSgRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.didiyun.compute.v1.CreateSgRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.didiyun.compute.v1.CreateSgRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.didiyun.compute.v1.CreateSgRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.didiyun.compute.v1.CreateSgRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.didiyun.compute.v1.CreateSgRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.didiyun.compute.v1.CreateSgRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code didi.cloud.compute.v1.CreateSgRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:didi.cloud.compute.v1.CreateSgRequest)
      com.didiyun.compute.v1.CreateSgRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.didiyun.compute.v1.SgOuterClass.internal_static_didi_cloud_compute_v1_CreateSgRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.didiyun.compute.v1.SgOuterClass.internal_static_didi_cloud_compute_v1_CreateSgRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.didiyun.compute.v1.CreateSgRequest.class, com.didiyun.compute.v1.CreateSgRequest.Builder.class);
    }

    // Construct using com.didiyun.compute.v1.CreateSgRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getSgRuleFieldBuilder();
        getDc2FieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (headerBuilder_ == null) {
        header_ = null;
      } else {
        header_ = null;
        headerBuilder_ = null;
      }
      name_ = "";

      vpcUuid_ = "";

      if (sgRuleBuilder_ == null) {
        sgRule_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000008);
      } else {
        sgRuleBuilder_.clear();
      }
      if (dc2Builder_ == null) {
        dc2_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000010);
      } else {
        dc2Builder_.clear();
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.didiyun.compute.v1.SgOuterClass.internal_static_didi_cloud_compute_v1_CreateSgRequest_descriptor;
    }

    @java.lang.Override
    public com.didiyun.compute.v1.CreateSgRequest getDefaultInstanceForType() {
      return com.didiyun.compute.v1.CreateSgRequest.getDefaultInstance();
    }

    @java.lang.Override
    public com.didiyun.compute.v1.CreateSgRequest build() {
      com.didiyun.compute.v1.CreateSgRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.didiyun.compute.v1.CreateSgRequest buildPartial() {
      com.didiyun.compute.v1.CreateSgRequest result = new com.didiyun.compute.v1.CreateSgRequest(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (headerBuilder_ == null) {
        result.header_ = header_;
      } else {
        result.header_ = headerBuilder_.build();
      }
      result.name_ = name_;
      result.vpcUuid_ = vpcUuid_;
      if (sgRuleBuilder_ == null) {
        if (((bitField0_ & 0x00000008) == 0x00000008)) {
          sgRule_ = java.util.Collections.unmodifiableList(sgRule_);
          bitField0_ = (bitField0_ & ~0x00000008);
        }
        result.sgRule_ = sgRule_;
      } else {
        result.sgRule_ = sgRuleBuilder_.build();
      }
      if (dc2Builder_ == null) {
        if (((bitField0_ & 0x00000010) == 0x00000010)) {
          dc2_ = java.util.Collections.unmodifiableList(dc2_);
          bitField0_ = (bitField0_ & ~0x00000010);
        }
        result.dc2_ = dc2_;
      } else {
        result.dc2_ = dc2Builder_.build();
      }
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.didiyun.compute.v1.CreateSgRequest) {
        return mergeFrom((com.didiyun.compute.v1.CreateSgRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.didiyun.compute.v1.CreateSgRequest other) {
      if (other == com.didiyun.compute.v1.CreateSgRequest.getDefaultInstance()) return this;
      if (other.hasHeader()) {
        mergeHeader(other.getHeader());
      }
      if (!other.getName().isEmpty()) {
        name_ = other.name_;
        onChanged();
      }
      if (!other.getVpcUuid().isEmpty()) {
        vpcUuid_ = other.vpcUuid_;
        onChanged();
      }
      if (sgRuleBuilder_ == null) {
        if (!other.sgRule_.isEmpty()) {
          if (sgRule_.isEmpty()) {
            sgRule_ = other.sgRule_;
            bitField0_ = (bitField0_ & ~0x00000008);
          } else {
            ensureSgRuleIsMutable();
            sgRule_.addAll(other.sgRule_);
          }
          onChanged();
        }
      } else {
        if (!other.sgRule_.isEmpty()) {
          if (sgRuleBuilder_.isEmpty()) {
            sgRuleBuilder_.dispose();
            sgRuleBuilder_ = null;
            sgRule_ = other.sgRule_;
            bitField0_ = (bitField0_ & ~0x00000008);
            sgRuleBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getSgRuleFieldBuilder() : null;
          } else {
            sgRuleBuilder_.addAllMessages(other.sgRule_);
          }
        }
      }
      if (dc2Builder_ == null) {
        if (!other.dc2_.isEmpty()) {
          if (dc2_.isEmpty()) {
            dc2_ = other.dc2_;
            bitField0_ = (bitField0_ & ~0x00000010);
          } else {
            ensureDc2IsMutable();
            dc2_.addAll(other.dc2_);
          }
          onChanged();
        }
      } else {
        if (!other.dc2_.isEmpty()) {
          if (dc2Builder_.isEmpty()) {
            dc2Builder_.dispose();
            dc2Builder_ = null;
            dc2_ = other.dc2_;
            bitField0_ = (bitField0_ & ~0x00000010);
            dc2Builder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getDc2FieldBuilder() : null;
          } else {
            dc2Builder_.addAllMessages(other.dc2_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.didiyun.compute.v1.CreateSgRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.didiyun.compute.v1.CreateSgRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private com.didiyun.base.v1.Header header_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.didiyun.base.v1.Header, com.didiyun.base.v1.Header.Builder, com.didiyun.base.v1.HeaderOrBuilder> headerBuilder_;
    /**
     * <pre>
     *公共的请求头
     * </pre>
     *
     * <code>.didi.cloud.base.v1.Header header = 1;</code>
     */
    public boolean hasHeader() {
      return headerBuilder_ != null || header_ != null;
    }
    /**
     * <pre>
     *公共的请求头
     * </pre>
     *
     * <code>.didi.cloud.base.v1.Header header = 1;</code>
     */
    public com.didiyun.base.v1.Header getHeader() {
      if (headerBuilder_ == null) {
        return header_ == null ? com.didiyun.base.v1.Header.getDefaultInstance() : header_;
      } else {
        return headerBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     *公共的请求头
     * </pre>
     *
     * <code>.didi.cloud.base.v1.Header header = 1;</code>
     */
    public Builder setHeader(com.didiyun.base.v1.Header value) {
      if (headerBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        header_ = value;
        onChanged();
      } else {
        headerBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <pre>
     *公共的请求头
     * </pre>
     *
     * <code>.didi.cloud.base.v1.Header header = 1;</code>
     */
    public Builder setHeader(
        com.didiyun.base.v1.Header.Builder builderForValue) {
      if (headerBuilder_ == null) {
        header_ = builderForValue.build();
        onChanged();
      } else {
        headerBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <pre>
     *公共的请求头
     * </pre>
     *
     * <code>.didi.cloud.base.v1.Header header = 1;</code>
     */
    public Builder mergeHeader(com.didiyun.base.v1.Header value) {
      if (headerBuilder_ == null) {
        if (header_ != null) {
          header_ =
            com.didiyun.base.v1.Header.newBuilder(header_).mergeFrom(value).buildPartial();
        } else {
          header_ = value;
        }
        onChanged();
      } else {
        headerBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <pre>
     *公共的请求头
     * </pre>
     *
     * <code>.didi.cloud.base.v1.Header header = 1;</code>
     */
    public Builder clearHeader() {
      if (headerBuilder_ == null) {
        header_ = null;
        onChanged();
      } else {
        header_ = null;
        headerBuilder_ = null;
      }

      return this;
    }
    /**
     * <pre>
     *公共的请求头
     * </pre>
     *
     * <code>.didi.cloud.base.v1.Header header = 1;</code>
     */
    public com.didiyun.base.v1.Header.Builder getHeaderBuilder() {
      
      onChanged();
      return getHeaderFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     *公共的请求头
     * </pre>
     *
     * <code>.didi.cloud.base.v1.Header header = 1;</code>
     */
    public com.didiyun.base.v1.HeaderOrBuilder getHeaderOrBuilder() {
      if (headerBuilder_ != null) {
        return headerBuilder_.getMessageOrBuilder();
      } else {
        return header_ == null ?
            com.didiyun.base.v1.Header.getDefaultInstance() : header_;
      }
    }
    /**
     * <pre>
     *公共的请求头
     * </pre>
     *
     * <code>.didi.cloud.base.v1.Header header = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.didiyun.base.v1.Header, com.didiyun.base.v1.Header.Builder, com.didiyun.base.v1.HeaderOrBuilder> 
        getHeaderFieldBuilder() {
      if (headerBuilder_ == null) {
        headerBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.didiyun.base.v1.Header, com.didiyun.base.v1.Header.Builder, com.didiyun.base.v1.HeaderOrBuilder>(
                getHeader(),
                getParentForChildren(),
                isClean());
        header_ = null;
      }
      return headerBuilder_;
    }

    private java.lang.Object name_ = "";
    /**
     * <pre>
     *SG名称
     * </pre>
     *
     * <code>string name = 2;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     *SG名称
     * </pre>
     *
     * <code>string name = 2;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     *SG名称
     * </pre>
     *
     * <code>string name = 2;</code>
     */
    public Builder setName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      name_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *SG名称
     * </pre>
     *
     * <code>string name = 2;</code>
     */
    public Builder clearName() {
      
      name_ = getDefaultInstance().getName();
      onChanged();
      return this;
    }
    /**
     * <pre>
     *SG名称
     * </pre>
     *
     * <code>string name = 2;</code>
     */
    public Builder setNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      name_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object vpcUuid_ = "";
    /**
     * <pre>
     *此SG要创建的VPC的uuid，不传则创建在指定region的默认VPC下
     * </pre>
     *
     * <code>string vpcUuid = 3;</code>
     */
    public java.lang.String getVpcUuid() {
      java.lang.Object ref = vpcUuid_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        vpcUuid_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     *此SG要创建的VPC的uuid，不传则创建在指定region的默认VPC下
     * </pre>
     *
     * <code>string vpcUuid = 3;</code>
     */
    public com.google.protobuf.ByteString
        getVpcUuidBytes() {
      java.lang.Object ref = vpcUuid_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        vpcUuid_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     *此SG要创建的VPC的uuid，不传则创建在指定region的默认VPC下
     * </pre>
     *
     * <code>string vpcUuid = 3;</code>
     */
    public Builder setVpcUuid(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      vpcUuid_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *此SG要创建的VPC的uuid，不传则创建在指定region的默认VPC下
     * </pre>
     *
     * <code>string vpcUuid = 3;</code>
     */
    public Builder clearVpcUuid() {
      
      vpcUuid_ = getDefaultInstance().getVpcUuid();
      onChanged();
      return this;
    }
    /**
     * <pre>
     *此SG要创建的VPC的uuid，不传则创建在指定region的默认VPC下
     * </pre>
     *
     * <code>string vpcUuid = 3;</code>
     */
    public Builder setVpcUuidBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      vpcUuid_ = value;
      onChanged();
      return this;
    }

    private java.util.List<com.didiyun.compute.v1.CreateSgRuleInput> sgRule_ =
      java.util.Collections.emptyList();
    private void ensureSgRuleIsMutable() {
      if (!((bitField0_ & 0x00000008) == 0x00000008)) {
        sgRule_ = new java.util.ArrayList<com.didiyun.compute.v1.CreateSgRuleInput>(sgRule_);
        bitField0_ |= 0x00000008;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.didiyun.compute.v1.CreateSgRuleInput, com.didiyun.compute.v1.CreateSgRuleInput.Builder, com.didiyun.compute.v1.CreateSgRuleInputOrBuilder> sgRuleBuilder_;

    /**
     * <pre>
     *同时在此SG下创建的规则信息
     * </pre>
     *
     * <code>repeated .didi.cloud.compute.v1.CreateSgRuleInput sgRule = 4;</code>
     */
    public java.util.List<com.didiyun.compute.v1.CreateSgRuleInput> getSgRuleList() {
      if (sgRuleBuilder_ == null) {
        return java.util.Collections.unmodifiableList(sgRule_);
      } else {
        return sgRuleBuilder_.getMessageList();
      }
    }
    /**
     * <pre>
     *同时在此SG下创建的规则信息
     * </pre>
     *
     * <code>repeated .didi.cloud.compute.v1.CreateSgRuleInput sgRule = 4;</code>
     */
    public int getSgRuleCount() {
      if (sgRuleBuilder_ == null) {
        return sgRule_.size();
      } else {
        return sgRuleBuilder_.getCount();
      }
    }
    /**
     * <pre>
     *同时在此SG下创建的规则信息
     * </pre>
     *
     * <code>repeated .didi.cloud.compute.v1.CreateSgRuleInput sgRule = 4;</code>
     */
    public com.didiyun.compute.v1.CreateSgRuleInput getSgRule(int index) {
      if (sgRuleBuilder_ == null) {
        return sgRule_.get(index);
      } else {
        return sgRuleBuilder_.getMessage(index);
      }
    }
    /**
     * <pre>
     *同时在此SG下创建的规则信息
     * </pre>
     *
     * <code>repeated .didi.cloud.compute.v1.CreateSgRuleInput sgRule = 4;</code>
     */
    public Builder setSgRule(
        int index, com.didiyun.compute.v1.CreateSgRuleInput value) {
      if (sgRuleBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureSgRuleIsMutable();
        sgRule_.set(index, value);
        onChanged();
      } else {
        sgRuleBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     *同时在此SG下创建的规则信息
     * </pre>
     *
     * <code>repeated .didi.cloud.compute.v1.CreateSgRuleInput sgRule = 4;</code>
     */
    public Builder setSgRule(
        int index, com.didiyun.compute.v1.CreateSgRuleInput.Builder builderForValue) {
      if (sgRuleBuilder_ == null) {
        ensureSgRuleIsMutable();
        sgRule_.set(index, builderForValue.build());
        onChanged();
      } else {
        sgRuleBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     *同时在此SG下创建的规则信息
     * </pre>
     *
     * <code>repeated .didi.cloud.compute.v1.CreateSgRuleInput sgRule = 4;</code>
     */
    public Builder addSgRule(com.didiyun.compute.v1.CreateSgRuleInput value) {
      if (sgRuleBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureSgRuleIsMutable();
        sgRule_.add(value);
        onChanged();
      } else {
        sgRuleBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <pre>
     *同时在此SG下创建的规则信息
     * </pre>
     *
     * <code>repeated .didi.cloud.compute.v1.CreateSgRuleInput sgRule = 4;</code>
     */
    public Builder addSgRule(
        int index, com.didiyun.compute.v1.CreateSgRuleInput value) {
      if (sgRuleBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureSgRuleIsMutable();
        sgRule_.add(index, value);
        onChanged();
      } else {
        sgRuleBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     *同时在此SG下创建的规则信息
     * </pre>
     *
     * <code>repeated .didi.cloud.compute.v1.CreateSgRuleInput sgRule = 4;</code>
     */
    public Builder addSgRule(
        com.didiyun.compute.v1.CreateSgRuleInput.Builder builderForValue) {
      if (sgRuleBuilder_ == null) {
        ensureSgRuleIsMutable();
        sgRule_.add(builderForValue.build());
        onChanged();
      } else {
        sgRuleBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     *同时在此SG下创建的规则信息
     * </pre>
     *
     * <code>repeated .didi.cloud.compute.v1.CreateSgRuleInput sgRule = 4;</code>
     */
    public Builder addSgRule(
        int index, com.didiyun.compute.v1.CreateSgRuleInput.Builder builderForValue) {
      if (sgRuleBuilder_ == null) {
        ensureSgRuleIsMutable();
        sgRule_.add(index, builderForValue.build());
        onChanged();
      } else {
        sgRuleBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     *同时在此SG下创建的规则信息
     * </pre>
     *
     * <code>repeated .didi.cloud.compute.v1.CreateSgRuleInput sgRule = 4;</code>
     */
    public Builder addAllSgRule(
        java.lang.Iterable<? extends com.didiyun.compute.v1.CreateSgRuleInput> values) {
      if (sgRuleBuilder_ == null) {
        ensureSgRuleIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, sgRule_);
        onChanged();
      } else {
        sgRuleBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <pre>
     *同时在此SG下创建的规则信息
     * </pre>
     *
     * <code>repeated .didi.cloud.compute.v1.CreateSgRuleInput sgRule = 4;</code>
     */
    public Builder clearSgRule() {
      if (sgRuleBuilder_ == null) {
        sgRule_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000008);
        onChanged();
      } else {
        sgRuleBuilder_.clear();
      }
      return this;
    }
    /**
     * <pre>
     *同时在此SG下创建的规则信息
     * </pre>
     *
     * <code>repeated .didi.cloud.compute.v1.CreateSgRuleInput sgRule = 4;</code>
     */
    public Builder removeSgRule(int index) {
      if (sgRuleBuilder_ == null) {
        ensureSgRuleIsMutable();
        sgRule_.remove(index);
        onChanged();
      } else {
        sgRuleBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <pre>
     *同时在此SG下创建的规则信息
     * </pre>
     *
     * <code>repeated .didi.cloud.compute.v1.CreateSgRuleInput sgRule = 4;</code>
     */
    public com.didiyun.compute.v1.CreateSgRuleInput.Builder getSgRuleBuilder(
        int index) {
      return getSgRuleFieldBuilder().getBuilder(index);
    }
    /**
     * <pre>
     *同时在此SG下创建的规则信息
     * </pre>
     *
     * <code>repeated .didi.cloud.compute.v1.CreateSgRuleInput sgRule = 4;</code>
     */
    public com.didiyun.compute.v1.CreateSgRuleInputOrBuilder getSgRuleOrBuilder(
        int index) {
      if (sgRuleBuilder_ == null) {
        return sgRule_.get(index);  } else {
        return sgRuleBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <pre>
     *同时在此SG下创建的规则信息
     * </pre>
     *
     * <code>repeated .didi.cloud.compute.v1.CreateSgRuleInput sgRule = 4;</code>
     */
    public java.util.List<? extends com.didiyun.compute.v1.CreateSgRuleInputOrBuilder> 
         getSgRuleOrBuilderList() {
      if (sgRuleBuilder_ != null) {
        return sgRuleBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(sgRule_);
      }
    }
    /**
     * <pre>
     *同时在此SG下创建的规则信息
     * </pre>
     *
     * <code>repeated .didi.cloud.compute.v1.CreateSgRuleInput sgRule = 4;</code>
     */
    public com.didiyun.compute.v1.CreateSgRuleInput.Builder addSgRuleBuilder() {
      return getSgRuleFieldBuilder().addBuilder(
          com.didiyun.compute.v1.CreateSgRuleInput.getDefaultInstance());
    }
    /**
     * <pre>
     *同时在此SG下创建的规则信息
     * </pre>
     *
     * <code>repeated .didi.cloud.compute.v1.CreateSgRuleInput sgRule = 4;</code>
     */
    public com.didiyun.compute.v1.CreateSgRuleInput.Builder addSgRuleBuilder(
        int index) {
      return getSgRuleFieldBuilder().addBuilder(
          index, com.didiyun.compute.v1.CreateSgRuleInput.getDefaultInstance());
    }
    /**
     * <pre>
     *同时在此SG下创建的规则信息
     * </pre>
     *
     * <code>repeated .didi.cloud.compute.v1.CreateSgRuleInput sgRule = 4;</code>
     */
    public java.util.List<com.didiyun.compute.v1.CreateSgRuleInput.Builder> 
         getSgRuleBuilderList() {
      return getSgRuleFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.didiyun.compute.v1.CreateSgRuleInput, com.didiyun.compute.v1.CreateSgRuleInput.Builder, com.didiyun.compute.v1.CreateSgRuleInputOrBuilder> 
        getSgRuleFieldBuilder() {
      if (sgRuleBuilder_ == null) {
        sgRuleBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.didiyun.compute.v1.CreateSgRuleInput, com.didiyun.compute.v1.CreateSgRuleInput.Builder, com.didiyun.compute.v1.CreateSgRuleInputOrBuilder>(
                sgRule_,
                ((bitField0_ & 0x00000008) == 0x00000008),
                getParentForChildren(),
                isClean());
        sgRule_ = null;
      }
      return sgRuleBuilder_;
    }

    private java.util.List<com.didiyun.compute.v1.CreateSgRequest.DC2> dc2_ =
      java.util.Collections.emptyList();
    private void ensureDc2IsMutable() {
      if (!((bitField0_ & 0x00000010) == 0x00000010)) {
        dc2_ = new java.util.ArrayList<com.didiyun.compute.v1.CreateSgRequest.DC2>(dc2_);
        bitField0_ |= 0x00000010;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.didiyun.compute.v1.CreateSgRequest.DC2, com.didiyun.compute.v1.CreateSgRequest.DC2.Builder, com.didiyun.compute.v1.CreateSgRequest.DC2OrBuilder> dc2Builder_;

    /**
     * <pre>
     *需要同时添加至此SG的DC2信息
     * </pre>
     *
     * <code>repeated .didi.cloud.compute.v1.CreateSgRequest.DC2 dc2 = 5;</code>
     */
    public java.util.List<com.didiyun.compute.v1.CreateSgRequest.DC2> getDc2List() {
      if (dc2Builder_ == null) {
        return java.util.Collections.unmodifiableList(dc2_);
      } else {
        return dc2Builder_.getMessageList();
      }
    }
    /**
     * <pre>
     *需要同时添加至此SG的DC2信息
     * </pre>
     *
     * <code>repeated .didi.cloud.compute.v1.CreateSgRequest.DC2 dc2 = 5;</code>
     */
    public int getDc2Count() {
      if (dc2Builder_ == null) {
        return dc2_.size();
      } else {
        return dc2Builder_.getCount();
      }
    }
    /**
     * <pre>
     *需要同时添加至此SG的DC2信息
     * </pre>
     *
     * <code>repeated .didi.cloud.compute.v1.CreateSgRequest.DC2 dc2 = 5;</code>
     */
    public com.didiyun.compute.v1.CreateSgRequest.DC2 getDc2(int index) {
      if (dc2Builder_ == null) {
        return dc2_.get(index);
      } else {
        return dc2Builder_.getMessage(index);
      }
    }
    /**
     * <pre>
     *需要同时添加至此SG的DC2信息
     * </pre>
     *
     * <code>repeated .didi.cloud.compute.v1.CreateSgRequest.DC2 dc2 = 5;</code>
     */
    public Builder setDc2(
        int index, com.didiyun.compute.v1.CreateSgRequest.DC2 value) {
      if (dc2Builder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureDc2IsMutable();
        dc2_.set(index, value);
        onChanged();
      } else {
        dc2Builder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     *需要同时添加至此SG的DC2信息
     * </pre>
     *
     * <code>repeated .didi.cloud.compute.v1.CreateSgRequest.DC2 dc2 = 5;</code>
     */
    public Builder setDc2(
        int index, com.didiyun.compute.v1.CreateSgRequest.DC2.Builder builderForValue) {
      if (dc2Builder_ == null) {
        ensureDc2IsMutable();
        dc2_.set(index, builderForValue.build());
        onChanged();
      } else {
        dc2Builder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     *需要同时添加至此SG的DC2信息
     * </pre>
     *
     * <code>repeated .didi.cloud.compute.v1.CreateSgRequest.DC2 dc2 = 5;</code>
     */
    public Builder addDc2(com.didiyun.compute.v1.CreateSgRequest.DC2 value) {
      if (dc2Builder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureDc2IsMutable();
        dc2_.add(value);
        onChanged();
      } else {
        dc2Builder_.addMessage(value);
      }
      return this;
    }
    /**
     * <pre>
     *需要同时添加至此SG的DC2信息
     * </pre>
     *
     * <code>repeated .didi.cloud.compute.v1.CreateSgRequest.DC2 dc2 = 5;</code>
     */
    public Builder addDc2(
        int index, com.didiyun.compute.v1.CreateSgRequest.DC2 value) {
      if (dc2Builder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureDc2IsMutable();
        dc2_.add(index, value);
        onChanged();
      } else {
        dc2Builder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     *需要同时添加至此SG的DC2信息
     * </pre>
     *
     * <code>repeated .didi.cloud.compute.v1.CreateSgRequest.DC2 dc2 = 5;</code>
     */
    public Builder addDc2(
        com.didiyun.compute.v1.CreateSgRequest.DC2.Builder builderForValue) {
      if (dc2Builder_ == null) {
        ensureDc2IsMutable();
        dc2_.add(builderForValue.build());
        onChanged();
      } else {
        dc2Builder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     *需要同时添加至此SG的DC2信息
     * </pre>
     *
     * <code>repeated .didi.cloud.compute.v1.CreateSgRequest.DC2 dc2 = 5;</code>
     */
    public Builder addDc2(
        int index, com.didiyun.compute.v1.CreateSgRequest.DC2.Builder builderForValue) {
      if (dc2Builder_ == null) {
        ensureDc2IsMutable();
        dc2_.add(index, builderForValue.build());
        onChanged();
      } else {
        dc2Builder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     *需要同时添加至此SG的DC2信息
     * </pre>
     *
     * <code>repeated .didi.cloud.compute.v1.CreateSgRequest.DC2 dc2 = 5;</code>
     */
    public Builder addAllDc2(
        java.lang.Iterable<? extends com.didiyun.compute.v1.CreateSgRequest.DC2> values) {
      if (dc2Builder_ == null) {
        ensureDc2IsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, dc2_);
        onChanged();
      } else {
        dc2Builder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <pre>
     *需要同时添加至此SG的DC2信息
     * </pre>
     *
     * <code>repeated .didi.cloud.compute.v1.CreateSgRequest.DC2 dc2 = 5;</code>
     */
    public Builder clearDc2() {
      if (dc2Builder_ == null) {
        dc2_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000010);
        onChanged();
      } else {
        dc2Builder_.clear();
      }
      return this;
    }
    /**
     * <pre>
     *需要同时添加至此SG的DC2信息
     * </pre>
     *
     * <code>repeated .didi.cloud.compute.v1.CreateSgRequest.DC2 dc2 = 5;</code>
     */
    public Builder removeDc2(int index) {
      if (dc2Builder_ == null) {
        ensureDc2IsMutable();
        dc2_.remove(index);
        onChanged();
      } else {
        dc2Builder_.remove(index);
      }
      return this;
    }
    /**
     * <pre>
     *需要同时添加至此SG的DC2信息
     * </pre>
     *
     * <code>repeated .didi.cloud.compute.v1.CreateSgRequest.DC2 dc2 = 5;</code>
     */
    public com.didiyun.compute.v1.CreateSgRequest.DC2.Builder getDc2Builder(
        int index) {
      return getDc2FieldBuilder().getBuilder(index);
    }
    /**
     * <pre>
     *需要同时添加至此SG的DC2信息
     * </pre>
     *
     * <code>repeated .didi.cloud.compute.v1.CreateSgRequest.DC2 dc2 = 5;</code>
     */
    public com.didiyun.compute.v1.CreateSgRequest.DC2OrBuilder getDc2OrBuilder(
        int index) {
      if (dc2Builder_ == null) {
        return dc2_.get(index);  } else {
        return dc2Builder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <pre>
     *需要同时添加至此SG的DC2信息
     * </pre>
     *
     * <code>repeated .didi.cloud.compute.v1.CreateSgRequest.DC2 dc2 = 5;</code>
     */
    public java.util.List<? extends com.didiyun.compute.v1.CreateSgRequest.DC2OrBuilder> 
         getDc2OrBuilderList() {
      if (dc2Builder_ != null) {
        return dc2Builder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(dc2_);
      }
    }
    /**
     * <pre>
     *需要同时添加至此SG的DC2信息
     * </pre>
     *
     * <code>repeated .didi.cloud.compute.v1.CreateSgRequest.DC2 dc2 = 5;</code>
     */
    public com.didiyun.compute.v1.CreateSgRequest.DC2.Builder addDc2Builder() {
      return getDc2FieldBuilder().addBuilder(
          com.didiyun.compute.v1.CreateSgRequest.DC2.getDefaultInstance());
    }
    /**
     * <pre>
     *需要同时添加至此SG的DC2信息
     * </pre>
     *
     * <code>repeated .didi.cloud.compute.v1.CreateSgRequest.DC2 dc2 = 5;</code>
     */
    public com.didiyun.compute.v1.CreateSgRequest.DC2.Builder addDc2Builder(
        int index) {
      return getDc2FieldBuilder().addBuilder(
          index, com.didiyun.compute.v1.CreateSgRequest.DC2.getDefaultInstance());
    }
    /**
     * <pre>
     *需要同时添加至此SG的DC2信息
     * </pre>
     *
     * <code>repeated .didi.cloud.compute.v1.CreateSgRequest.DC2 dc2 = 5;</code>
     */
    public java.util.List<com.didiyun.compute.v1.CreateSgRequest.DC2.Builder> 
         getDc2BuilderList() {
      return getDc2FieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.didiyun.compute.v1.CreateSgRequest.DC2, com.didiyun.compute.v1.CreateSgRequest.DC2.Builder, com.didiyun.compute.v1.CreateSgRequest.DC2OrBuilder> 
        getDc2FieldBuilder() {
      if (dc2Builder_ == null) {
        dc2Builder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.didiyun.compute.v1.CreateSgRequest.DC2, com.didiyun.compute.v1.CreateSgRequest.DC2.Builder, com.didiyun.compute.v1.CreateSgRequest.DC2OrBuilder>(
                dc2_,
                ((bitField0_ & 0x00000010) == 0x00000010),
                getParentForChildren(),
                isClean());
        dc2_ = null;
      }
      return dc2Builder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:didi.cloud.compute.v1.CreateSgRequest)
  }

  // @@protoc_insertion_point(class_scope:didi.cloud.compute.v1.CreateSgRequest)
  private static final com.didiyun.compute.v1.CreateSgRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.didiyun.compute.v1.CreateSgRequest();
  }

  public static com.didiyun.compute.v1.CreateSgRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<CreateSgRequest>
      PARSER = new com.google.protobuf.AbstractParser<CreateSgRequest>() {
    @java.lang.Override
    public CreateSgRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new CreateSgRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<CreateSgRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<CreateSgRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.didiyun.compute.v1.CreateSgRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

