// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: compute/v1/ebs.proto

package com.didiyun.compute.v1;

public interface CreateEbsRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:didi.cloud.compute.v1.CreateEbsRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   *公共的请求头
   * </pre>
   *
   * <code>.didi.cloud.base.v1.Header header = 1;</code>
   */
  boolean hasHeader();
  /**
   * <pre>
   *公共的请求头
   * </pre>
   *
   * <code>.didi.cloud.base.v1.Header header = 1;</code>
   */
  com.didiyun.base.v1.Header getHeader();
  /**
   * <pre>
   *公共的请求头
   * </pre>
   *
   * <code>.didi.cloud.base.v1.Header header = 1;</code>
   */
  com.didiyun.base.v1.HeaderOrBuilder getHeaderOrBuilder();

  /**
   * <pre>
   *创建EBS个数
   * </pre>
   *
   * <code>int32 count = 2;</code>
   */
  int getCount();

  /**
   * <pre>
   *是否设置DC2自动续费
   * </pre>
   *
   * <code>bool autoContinue = 3;</code>
   */
  boolean getAutoContinue();

  /**
   * <pre>
   *购买包月时长，单位为月，不传或传0表示后付费
   * </pre>
   *
   * <code>int32 payPeriod = 4;</code>
   */
  int getPayPeriod();

  /**
   * <pre>
   *优惠券Id
   * </pre>
   *
   * <code>string couponId = 5;</code>
   */
  java.lang.String getCouponId();
  /**
   * <pre>
   *优惠券Id
   * </pre>
   *
   * <code>string couponId = 5;</code>
   */
  com.google.protobuf.ByteString
      getCouponIdBytes();

  /**
   * <pre>
   *EBS名称
   * </pre>
   *
   * <code>string name = 6;</code>
   */
  java.lang.String getName();
  /**
   * <pre>
   *EBS名称
   * </pre>
   *
   * <code>string name = 6;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <pre>
   *EBS大小
   * </pre>
   *
   * <code>int64 size = 7;</code>
   */
  long getSize();

  /**
   * <pre>
   *EBS类型
   * </pre>
   *
   * <code>string diskType = 8;</code>
   */
  java.lang.String getDiskType();
  /**
   * <pre>
   *EBS类型
   * </pre>
   *
   * <code>string diskType = 8;</code>
   */
  com.google.protobuf.ByteString
      getDiskTypeBytes();

  /**
   * <pre>
   *通过此快照创建EBS
   * </pre>
   *
   * <code>string snapUuid = 9;</code>
   */
  java.lang.String getSnapUuid();
  /**
   * <pre>
   *通过此快照创建EBS
   * </pre>
   *
   * <code>string snapUuid = 9;</code>
   */
  com.google.protobuf.ByteString
      getSnapUuidBytes();

  /**
   * <pre>
   *创建此EBS实例同时将其绑定至该DC2
   * </pre>
   *
   * <code>string dc2Uuid = 10;</code>
   */
  java.lang.String getDc2Uuid();
  /**
   * <pre>
   *创建此EBS实例同时将其绑定至该DC2
   * </pre>
   *
   * <code>string dc2Uuid = 10;</code>
   */
  com.google.protobuf.ByteString
      getDc2UuidBytes();

  /**
   * <pre>
   *EBS标签
   * </pre>
   *
   * <code>repeated string tags = 11;</code>
   */
  java.util.List<java.lang.String>
      getTagsList();
  /**
   * <pre>
   *EBS标签
   * </pre>
   *
   * <code>repeated string tags = 11;</code>
   */
  int getTagsCount();
  /**
   * <pre>
   *EBS标签
   * </pre>
   *
   * <code>repeated string tags = 11;</code>
   */
  java.lang.String getTags(int index);
  /**
   * <pre>
   *EBS标签
   * </pre>
   *
   * <code>repeated string tags = 11;</code>
   */
  com.google.protobuf.ByteString
      getTagsBytes(int index);
}
