// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: compute/v1/ebs.proto

package com.didiyun.compute.v1;

public final class EbsOuterClass {
  private EbsOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_didi_cloud_compute_v1_ListEbsRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_didi_cloud_compute_v1_ListEbsRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_didi_cloud_compute_v1_ListEbsCondition_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_didi_cloud_compute_v1_ListEbsCondition_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_didi_cloud_compute_v1_ListEbsResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_didi_cloud_compute_v1_ListEbsResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_didi_cloud_compute_v1_GetEbsByUuidRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_didi_cloud_compute_v1_GetEbsByUuidRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_didi_cloud_compute_v1_GetEbsByUuidResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_didi_cloud_compute_v1_GetEbsByUuidResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_didi_cloud_compute_v1_GetEbsTotalCntRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_didi_cloud_compute_v1_GetEbsTotalCntRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_didi_cloud_compute_v1_GetEbsTotalCntResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_didi_cloud_compute_v1_GetEbsTotalCntResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_didi_cloud_compute_v1_CreateEbsRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_didi_cloud_compute_v1_CreateEbsRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_didi_cloud_compute_v1_CreateEbsResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_didi_cloud_compute_v1_CreateEbsResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_didi_cloud_compute_v1_DeleteEbsRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_didi_cloud_compute_v1_DeleteEbsRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_didi_cloud_compute_v1_DeleteEbsRequest_Input_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_didi_cloud_compute_v1_DeleteEbsRequest_Input_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_didi_cloud_compute_v1_DeleteEbsResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_didi_cloud_compute_v1_DeleteEbsResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_didi_cloud_compute_v1_AttachEbsRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_didi_cloud_compute_v1_AttachEbsRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_didi_cloud_compute_v1_AttachEbsRequest_Input_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_didi_cloud_compute_v1_AttachEbsRequest_Input_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_didi_cloud_compute_v1_AttachEbsResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_didi_cloud_compute_v1_AttachEbsResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_didi_cloud_compute_v1_DetachEbsRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_didi_cloud_compute_v1_DetachEbsRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_didi_cloud_compute_v1_DetachEbsRequest_Input_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_didi_cloud_compute_v1_DetachEbsRequest_Input_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_didi_cloud_compute_v1_DetachEbsResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_didi_cloud_compute_v1_DetachEbsResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_didi_cloud_compute_v1_ChangeEbsSizeRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_didi_cloud_compute_v1_ChangeEbsSizeRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_didi_cloud_compute_v1_ChangeEbsSizeRequest_Input_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_didi_cloud_compute_v1_ChangeEbsSizeRequest_Input_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_didi_cloud_compute_v1_ChangeEbsSizeResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_didi_cloud_compute_v1_ChangeEbsSizeResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_didi_cloud_compute_v1_ChangeEbsNameRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_didi_cloud_compute_v1_ChangeEbsNameRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_didi_cloud_compute_v1_ChangeEbsNameRequest_Input_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_didi_cloud_compute_v1_ChangeEbsNameRequest_Input_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_didi_cloud_compute_v1_ChangeEbsNameResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_didi_cloud_compute_v1_ChangeEbsNameResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\024compute/v1/ebs.proto\022\025didi.cloud.compu" +
      "te.v1\032\022base/v1/base.proto\032\027compute/v1/co" +
      "mmon.proto\032\034google/api/annotations.proto" +
      "\"\250\001\n\016ListEbsRequest\022*\n\006header\030\001 \001(\0132\032.di" +
      "di.cloud.base.v1.Header\022\r\n\005start\030\002 \001(\005\022\r" +
      "\n\005limit\030\003 \001(\005\022\020\n\010simplify\030\004 \001(\010\022:\n\tcondi" +
      "tion\030\005 \001(\0132\'.didi.cloud.compute.v1.ListE" +
      "bsCondition\"$\n\020ListEbsCondition\022\020\n\010dc2Uu" +
      "ids\030\001 \003(\t\"i\n\017ListEbsResponse\022(\n\005error\030\001 " +
      "\001(\0132\031.didi.cloud.base.v1.Error\022,\n\004data\030\002" +
      " \003(\0132\036.didi.cloud.compute.v1.EbsInfo\"R\n\023" +
      "GetEbsByUuidRequest\022*\n\006header\030\001 \001(\0132\032.di" +
      "di.cloud.base.v1.Header\022\017\n\007ebsUuid\030\002 \001(\t" +
      "\"n\n\024GetEbsByUuidResponse\022(\n\005error\030\001 \001(\0132" +
      "\031.didi.cloud.base.v1.Error\022,\n\004data\030\002 \003(\013" +
      "2\036.didi.cloud.compute.v1.EbsInfo\"U\n\025GetE" +
      "bsTotalCntRequest\022*\n\006header\030\001 \001(\0132\032.didi" +
      ".cloud.base.v1.Header\022\020\n\010dc2Uuids\030\002 \003(\t\"" +
      "u\n\026GetEbsTotalCntResponse\022(\n\005error\030\001 \001(\013" +
      "2\031.didi.cloud.base.v1.Error\0221\n\004data\030\002 \003(" +
      "\0132#.didi.cloud.compute.v1.TotalCntInfo\"\347" +
      "\001\n\020CreateEbsRequest\022*\n\006header\030\001 \001(\0132\032.di" +
      "di.cloud.base.v1.Header\022\r\n\005count\030\002 \001(\005\022\024" +
      "\n\014autoContinue\030\003 \001(\010\022\021\n\tpayPeriod\030\004 \001(\005\022" +
      "\020\n\010couponId\030\005 \001(\t\022\014\n\004name\030\006 \001(\t\022\014\n\004size\030" +
      "\007 \001(\003\022\020\n\010diskType\030\010 \001(\t\022\020\n\010snapUuid\030\t \001(" +
      "\t\022\017\n\007dc2Uuid\030\n \001(\t\022\014\n\004tags\030\013 \003(\t\"h\n\021Crea" +
      "teEbsResponse\022(\n\005error\030\001 \001(\0132\031.didi.clou" +
      "d.base.v1.Error\022)\n\004data\030\002 \003(\0132\033.didi.clo" +
      "ud.base.v1.JobInfo\"\224\001\n\020DeleteEbsRequest\022" +
      "*\n\006header\030\001 \001(\0132\032.didi.cloud.base.v1.Hea" +
      "der\022:\n\003ebs\030\002 \003(\0132-.didi.cloud.compute.v1" +
      ".DeleteEbsRequest.Input\032\030\n\005Input\022\017\n\007ebsU" +
      "uid\030\001 \001(\t\"h\n\021DeleteEbsResponse\022(\n\005error\030" +
      "\001 \001(\0132\031.didi.cloud.base.v1.Error\022)\n\004data" +
      "\030\002 \003(\0132\033.didi.cloud.base.v1.JobInfo\"\245\001\n\020" +
      "AttachEbsRequest\022*\n\006header\030\001 \001(\0132\032.didi." +
      "cloud.base.v1.Header\022:\n\003ebs\030\002 \003(\0132-.didi" +
      ".cloud.compute.v1.AttachEbsRequest.Input" +
      "\032)\n\005Input\022\017\n\007ebsUuid\030\001 \001(\t\022\017\n\007dc2Uuid\030\002 " +
      "\001(\t\"h\n\021AttachEbsResponse\022(\n\005error\030\001 \001(\0132" +
      "\031.didi.cloud.base.v1.Error\022)\n\004data\030\002 \003(\013" +
      "2\033.didi.cloud.base.v1.JobInfo\"\224\001\n\020Detach" +
      "EbsRequest\022*\n\006header\030\001 \001(\0132\032.didi.cloud." +
      "base.v1.Header\022:\n\003ebs\030\002 \003(\0132-.didi.cloud" +
      ".compute.v1.DetachEbsRequest.Input\032\030\n\005In" +
      "put\022\017\n\007ebsUuid\030\001 \001(\t\"h\n\021DetachEbsRespons" +
      "e\022(\n\005error\030\001 \001(\0132\031.didi.cloud.base.v1.Er" +
      "ror\022)\n\004data\030\002 \003(\0132\033.didi.cloud.base.v1.J" +
      "obInfo\"\274\001\n\024ChangeEbsSizeRequest\022*\n\006heade" +
      "r\030\001 \001(\0132\032.didi.cloud.base.v1.Header\022\020\n\010c" +
      "ouponId\030\002 \001(\t\022>\n\003ebs\030\003 \003(\01321.didi.cloud." +
      "compute.v1.ChangeEbsSizeRequest.Input\032&\n" +
      "\005Input\022\017\n\007ebsUuid\030\001 \001(\t\022\014\n\004size\030\002 \001(\003\"l\n" +
      "\025ChangeEbsSizeResponse\022(\n\005error\030\001 \001(\0132\031." +
      "didi.cloud.base.v1.Error\022)\n\004data\030\002 \003(\0132\033" +
      ".didi.cloud.base.v1.JobInfo\"\252\001\n\024ChangeEb" +
      "sNameRequest\022*\n\006header\030\001 \001(\0132\032.didi.clou" +
      "d.base.v1.Header\022>\n\003ebs\030\002 \003(\01321.didi.clo" +
      "ud.compute.v1.ChangeEbsNameRequest.Input" +
      "\032&\n\005Input\022\017\n\007ebsUuid\030\001 \001(\t\022\014\n\004name\030\002 \001(\t" +
      "\"l\n\025ChangeEbsNameResponse\022(\n\005error\030\001 \001(\013" +
      "2\031.didi.cloud.base.v1.Error\022)\n\004data\030\002 \003(" +
      "\0132\033.didi.cloud.base.v1.JobInfo2\353\t\n\003Ebs\022|" +
      "\n\007ListEbs\022%.didi.cloud.compute.v1.ListEb" +
      "sRequest\032&.didi.cloud.compute.v1.ListEbs" +
      "Response\"\"\202\323\344\223\002\034\"\032dicloud/i/storage/ebs/" +
      "list\022\206\001\n\014GetEbsByUuid\022*.didi.cloud.compu" +
      "te.v1.GetEbsByUuidRequest\032+.didi.cloud.c" +
      "ompute.v1.GetEbsByUuidResponse\"\035\202\323\344\223\002\027\022\025" +
      "dicloud/i/storage/ebs\022\222\001\n\016GetEbsTotalCnt" +
      "\022,.didi.cloud.compute.v1.GetEbsTotalCntR" +
      "equest\032-.didi.cloud.compute.v1.GetEbsTot" +
      "alCntResponse\"#\202\323\344\223\002\035\"\033dicloud/i/storage" +
      "/ebs/count\022\204\001\n\tCreateEbs\022\'.didi.cloud.co" +
      "mpute.v1.CreateEbsRequest\032(.didi.cloud.c" +
      "ompute.v1.CreateEbsResponse\"$\202\323\344\223\002\036\"\034dic" +
      "loud/i/storage/ebs/assign\022\204\001\n\tDeleteEbs\022" +
      "\'.didi.cloud.compute.v1.DeleteEbsRequest" +
      "\032(.didi.cloud.compute.v1.DeleteEbsRespon" +
      "se\"$\202\323\344\223\002\036\"\034dicloud/i/storage/ebs/delete" +
      "\022\204\001\n\tAttachEbs\022\'.didi.cloud.compute.v1.A" +
      "ttachEbsRequest\032(.didi.cloud.compute.v1." +
      "AttachEbsResponse\"$\202\323\344\223\002\036\"\034dicloud/i/sto" +
      "rage/ebs/attach\022\204\001\n\tDetachEbs\022\'.didi.clo" +
      "ud.compute.v1.DetachEbsRequest\032(.didi.cl" +
      "oud.compute.v1.DetachEbsResponse\"$\202\323\344\223\002\036" +
      "\"\034dicloud/i/storage/ebs/detach\022\224\001\n\rChang" +
      "eEbsSize\022+.didi.cloud.compute.v1.ChangeE" +
      "bsSizeRequest\032,.didi.cloud.compute.v1.Ch" +
      "angeEbsSizeResponse\"(\202\323\344\223\002\"\" dicloud/i/s" +
      "torage/ebs/changeSize\022\224\001\n\rChangeEbsName\022" +
      "+.didi.cloud.compute.v1.ChangeEbsNameReq" +
      "uest\032,.didi.cloud.compute.v1.ChangeEbsNa" +
      "meResponse\"(\202\323\344\223\002\"\" dicloud/i/storage/eb" +
      "s/changeNameB\207\001\n\026com.didiyun.compute.v1P" +
      "\001Z4github.com/didiyun/didiyun-go-sdk/com" +
      "pute/v1;compute\370\001\001\252\002\027Didi.Dicloud.Comput" +
      "e.V1\312\002\027Didi\\Dicloud\\Compute\\V1b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.didiyun.base.v1.Base.getDescriptor(),
          com.didiyun.compute.v1.CommonOuterClass.getDescriptor(),
          com.google.api.AnnotationsProto.getDescriptor(),
        }, assigner);
    internal_static_didi_cloud_compute_v1_ListEbsRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_didi_cloud_compute_v1_ListEbsRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_didi_cloud_compute_v1_ListEbsRequest_descriptor,
        new java.lang.String[] { "Header", "Start", "Limit", "Simplify", "Condition", });
    internal_static_didi_cloud_compute_v1_ListEbsCondition_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_didi_cloud_compute_v1_ListEbsCondition_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_didi_cloud_compute_v1_ListEbsCondition_descriptor,
        new java.lang.String[] { "Dc2Uuids", });
    internal_static_didi_cloud_compute_v1_ListEbsResponse_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_didi_cloud_compute_v1_ListEbsResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_didi_cloud_compute_v1_ListEbsResponse_descriptor,
        new java.lang.String[] { "Error", "Data", });
    internal_static_didi_cloud_compute_v1_GetEbsByUuidRequest_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_didi_cloud_compute_v1_GetEbsByUuidRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_didi_cloud_compute_v1_GetEbsByUuidRequest_descriptor,
        new java.lang.String[] { "Header", "EbsUuid", });
    internal_static_didi_cloud_compute_v1_GetEbsByUuidResponse_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_didi_cloud_compute_v1_GetEbsByUuidResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_didi_cloud_compute_v1_GetEbsByUuidResponse_descriptor,
        new java.lang.String[] { "Error", "Data", });
    internal_static_didi_cloud_compute_v1_GetEbsTotalCntRequest_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_didi_cloud_compute_v1_GetEbsTotalCntRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_didi_cloud_compute_v1_GetEbsTotalCntRequest_descriptor,
        new java.lang.String[] { "Header", "Dc2Uuids", });
    internal_static_didi_cloud_compute_v1_GetEbsTotalCntResponse_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_didi_cloud_compute_v1_GetEbsTotalCntResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_didi_cloud_compute_v1_GetEbsTotalCntResponse_descriptor,
        new java.lang.String[] { "Error", "Data", });
    internal_static_didi_cloud_compute_v1_CreateEbsRequest_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_didi_cloud_compute_v1_CreateEbsRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_didi_cloud_compute_v1_CreateEbsRequest_descriptor,
        new java.lang.String[] { "Header", "Count", "AutoContinue", "PayPeriod", "CouponId", "Name", "Size", "DiskType", "SnapUuid", "Dc2Uuid", "Tags", });
    internal_static_didi_cloud_compute_v1_CreateEbsResponse_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_didi_cloud_compute_v1_CreateEbsResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_didi_cloud_compute_v1_CreateEbsResponse_descriptor,
        new java.lang.String[] { "Error", "Data", });
    internal_static_didi_cloud_compute_v1_DeleteEbsRequest_descriptor =
      getDescriptor().getMessageTypes().get(9);
    internal_static_didi_cloud_compute_v1_DeleteEbsRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_didi_cloud_compute_v1_DeleteEbsRequest_descriptor,
        new java.lang.String[] { "Header", "Ebs", });
    internal_static_didi_cloud_compute_v1_DeleteEbsRequest_Input_descriptor =
      internal_static_didi_cloud_compute_v1_DeleteEbsRequest_descriptor.getNestedTypes().get(0);
    internal_static_didi_cloud_compute_v1_DeleteEbsRequest_Input_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_didi_cloud_compute_v1_DeleteEbsRequest_Input_descriptor,
        new java.lang.String[] { "EbsUuid", });
    internal_static_didi_cloud_compute_v1_DeleteEbsResponse_descriptor =
      getDescriptor().getMessageTypes().get(10);
    internal_static_didi_cloud_compute_v1_DeleteEbsResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_didi_cloud_compute_v1_DeleteEbsResponse_descriptor,
        new java.lang.String[] { "Error", "Data", });
    internal_static_didi_cloud_compute_v1_AttachEbsRequest_descriptor =
      getDescriptor().getMessageTypes().get(11);
    internal_static_didi_cloud_compute_v1_AttachEbsRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_didi_cloud_compute_v1_AttachEbsRequest_descriptor,
        new java.lang.String[] { "Header", "Ebs", });
    internal_static_didi_cloud_compute_v1_AttachEbsRequest_Input_descriptor =
      internal_static_didi_cloud_compute_v1_AttachEbsRequest_descriptor.getNestedTypes().get(0);
    internal_static_didi_cloud_compute_v1_AttachEbsRequest_Input_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_didi_cloud_compute_v1_AttachEbsRequest_Input_descriptor,
        new java.lang.String[] { "EbsUuid", "Dc2Uuid", });
    internal_static_didi_cloud_compute_v1_AttachEbsResponse_descriptor =
      getDescriptor().getMessageTypes().get(12);
    internal_static_didi_cloud_compute_v1_AttachEbsResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_didi_cloud_compute_v1_AttachEbsResponse_descriptor,
        new java.lang.String[] { "Error", "Data", });
    internal_static_didi_cloud_compute_v1_DetachEbsRequest_descriptor =
      getDescriptor().getMessageTypes().get(13);
    internal_static_didi_cloud_compute_v1_DetachEbsRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_didi_cloud_compute_v1_DetachEbsRequest_descriptor,
        new java.lang.String[] { "Header", "Ebs", });
    internal_static_didi_cloud_compute_v1_DetachEbsRequest_Input_descriptor =
      internal_static_didi_cloud_compute_v1_DetachEbsRequest_descriptor.getNestedTypes().get(0);
    internal_static_didi_cloud_compute_v1_DetachEbsRequest_Input_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_didi_cloud_compute_v1_DetachEbsRequest_Input_descriptor,
        new java.lang.String[] { "EbsUuid", });
    internal_static_didi_cloud_compute_v1_DetachEbsResponse_descriptor =
      getDescriptor().getMessageTypes().get(14);
    internal_static_didi_cloud_compute_v1_DetachEbsResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_didi_cloud_compute_v1_DetachEbsResponse_descriptor,
        new java.lang.String[] { "Error", "Data", });
    internal_static_didi_cloud_compute_v1_ChangeEbsSizeRequest_descriptor =
      getDescriptor().getMessageTypes().get(15);
    internal_static_didi_cloud_compute_v1_ChangeEbsSizeRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_didi_cloud_compute_v1_ChangeEbsSizeRequest_descriptor,
        new java.lang.String[] { "Header", "CouponId", "Ebs", });
    internal_static_didi_cloud_compute_v1_ChangeEbsSizeRequest_Input_descriptor =
      internal_static_didi_cloud_compute_v1_ChangeEbsSizeRequest_descriptor.getNestedTypes().get(0);
    internal_static_didi_cloud_compute_v1_ChangeEbsSizeRequest_Input_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_didi_cloud_compute_v1_ChangeEbsSizeRequest_Input_descriptor,
        new java.lang.String[] { "EbsUuid", "Size", });
    internal_static_didi_cloud_compute_v1_ChangeEbsSizeResponse_descriptor =
      getDescriptor().getMessageTypes().get(16);
    internal_static_didi_cloud_compute_v1_ChangeEbsSizeResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_didi_cloud_compute_v1_ChangeEbsSizeResponse_descriptor,
        new java.lang.String[] { "Error", "Data", });
    internal_static_didi_cloud_compute_v1_ChangeEbsNameRequest_descriptor =
      getDescriptor().getMessageTypes().get(17);
    internal_static_didi_cloud_compute_v1_ChangeEbsNameRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_didi_cloud_compute_v1_ChangeEbsNameRequest_descriptor,
        new java.lang.String[] { "Header", "Ebs", });
    internal_static_didi_cloud_compute_v1_ChangeEbsNameRequest_Input_descriptor =
      internal_static_didi_cloud_compute_v1_ChangeEbsNameRequest_descriptor.getNestedTypes().get(0);
    internal_static_didi_cloud_compute_v1_ChangeEbsNameRequest_Input_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_didi_cloud_compute_v1_ChangeEbsNameRequest_Input_descriptor,
        new java.lang.String[] { "EbsUuid", "Name", });
    internal_static_didi_cloud_compute_v1_ChangeEbsNameResponse_descriptor =
      getDescriptor().getMessageTypes().get(18);
    internal_static_didi_cloud_compute_v1_ChangeEbsNameResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_didi_cloud_compute_v1_ChangeEbsNameResponse_descriptor,
        new java.lang.String[] { "Error", "Data", });
    com.google.protobuf.ExtensionRegistry registry =
        com.google.protobuf.ExtensionRegistry.newInstance();
    registry.add(com.google.api.AnnotationsProto.http);
    com.google.protobuf.Descriptors.FileDescriptor
        .internalUpdateFileDescriptor(descriptor, registry);
    com.didiyun.base.v1.Base.getDescriptor();
    com.didiyun.compute.v1.CommonOuterClass.getDescriptor();
    com.google.api.AnnotationsProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
