// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: compute/v1/sg.proto

package com.didiyun.compute.v1;

public interface GetSgRuleTotalCntRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:didi.cloud.compute.v1.GetSgRuleTotalCntRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   *公共的请求头
   * </pre>
   *
   * <code>.didi.cloud.base.v1.Header header = 1;</code>
   */
  boolean hasHeader();
  /**
   * <pre>
   *公共的请求头
   * </pre>
   *
   * <code>.didi.cloud.base.v1.Header header = 1;</code>
   */
  com.didiyun.base.v1.Header getHeader();
  /**
   * <pre>
   *公共的请求头
   * </pre>
   *
   * <code>.didi.cloud.base.v1.Header header = 1;</code>
   */
  com.didiyun.base.v1.HeaderOrBuilder getHeaderOrBuilder();

  /**
   * <pre>
   *查看此SG下的SGRule数量
   * </pre>
   *
   * <code>string sgUuid = 2;</code>
   */
  java.lang.String getSgUuid();
  /**
   * <pre>
   *查看此SG下的SGRule数量
   * </pre>
   *
   * <code>string sgUuid = 2;</code>
   */
  com.google.protobuf.ByteString
      getSgUuidBytes();

  /**
   * <pre>
   *查看此DC2遵循的SGRule数量
   * </pre>
   *
   * <code>string dc2Uuid = 3;</code>
   */
  java.lang.String getDc2Uuid();
  /**
   * <pre>
   *查看此DC2遵循的SGRule数量
   * </pre>
   *
   * <code>string dc2Uuid = 3;</code>
   */
  com.google.protobuf.ByteString
      getDc2UuidBytes();

  /**
   * <pre>
   *要查询的SGRule类型，"Ingress"为入方向，"Egress"为出方向
   * </pre>
   *
   * <code>string type = 4;</code>
   */
  java.lang.String getType();
  /**
   * <pre>
   *要查询的SGRule类型，"Ingress"为入方向，"Egress"为出方向
   * </pre>
   *
   * <code>string type = 4;</code>
   */
  com.google.protobuf.ByteString
      getTypeBytes();
}
