// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: compute/v1/snap.proto

package com.didiyun.compute.v1;

public interface ListSnapshotConditionOrBuilder extends
    // @@protoc_insertion_point(interface_extends:didi.cloud.compute.v1.ListSnapshotCondition)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   *查询此EBS上的快照
   * </pre>
   *
   * <code>string ebsUuid = 1;</code>
   */
  java.lang.String getEbsUuid();
  /**
   * <pre>
   *查询此EBS上的快照
   * </pre>
   *
   * <code>string ebsUuid = 1;</code>
   */
  com.google.protobuf.ByteString
      getEbsUuidBytes();

  /**
   * <pre>
   *查询快照的名称，模糊匹配
   * </pre>
   *
   * <code>string snapName = 2;</code>
   */
  java.lang.String getSnapName();
  /**
   * <pre>
   *查询快照的名称，模糊匹配
   * </pre>
   *
   * <code>string snapName = 2;</code>
   */
  com.google.protobuf.ByteString
      getSnapNameBytes();

  /**
   * <pre>
   *查询此dc2的根盘以及数据盘的快照
   * </pre>
   *
   * <code>string dc2Uuid = 3;</code>
   */
  java.lang.String getDc2Uuid();
  /**
   * <pre>
   *查询此dc2的根盘以及数据盘的快照
   * </pre>
   *
   * <code>string dc2Uuid = 3;</code>
   */
  com.google.protobuf.ByteString
      getDc2UuidBytes();
}
