// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: compute/v1/dc2.proto

package com.didiyun.compute.v1;

public interface ListDc2ConditionOrBuilder extends
    // @@protoc_insertion_point(interface_extends:didi.cloud.compute.v1.ListDc2Condition)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   *精确匹配内网IP
   * </pre>
   *
   * <code>string ip = 1;</code>
   */
  java.lang.String getIp();
  /**
   * <pre>
   *精确匹配内网IP
   * </pre>
   *
   * <code>string ip = 1;</code>
   */
  com.google.protobuf.ByteString
      getIpBytes();

  /**
   * <pre>
   *精确匹配公司EIP
   * </pre>
   *
   * <code>string eip = 2;</code>
   */
  java.lang.String getEip();
  /**
   * <pre>
   *精确匹配公司EIP
   * </pre>
   *
   * <code>string eip = 2;</code>
   */
  com.google.protobuf.ByteString
      getEipBytes();

  /**
   * <pre>
   *模糊匹配dc2名字
   * </pre>
   *
   * <code>string dc2name = 3;</code>
   */
  java.lang.String getDc2Name();
  /**
   * <pre>
   *模糊匹配dc2名字
   * </pre>
   *
   * <code>string dc2name = 3;</code>
   */
  com.google.protobuf.ByteString
      getDc2NameBytes();

  /**
   * <pre>
   *查询对应vpc列表下的dc2, vpc UUID支持
   * </pre>
   *
   * <code>repeated string vpcUuids = 4;</code>
   */
  java.util.List<java.lang.String>
      getVpcUuidsList();
  /**
   * <pre>
   *查询对应vpc列表下的dc2, vpc UUID支持
   * </pre>
   *
   * <code>repeated string vpcUuids = 4;</code>
   */
  int getVpcUuidsCount();
  /**
   * <pre>
   *查询对应vpc列表下的dc2, vpc UUID支持
   * </pre>
   *
   * <code>repeated string vpcUuids = 4;</code>
   */
  java.lang.String getVpcUuids(int index);
  /**
   * <pre>
   *查询对应vpc列表下的dc2, vpc UUID支持
   * </pre>
   *
   * <code>repeated string vpcUuids = 4;</code>
   */
  com.google.protobuf.ByteString
      getVpcUuidsBytes(int index);

  /**
   * <pre>
   *查询指定vpc下的dc2，vpc UUID支持
   * </pre>
   *
   * <code>string vpcUuid = 5;</code>
   */
  java.lang.String getVpcUuid();
  /**
   * <pre>
   *查询指定vpc下的dc2，vpc UUID支持
   * </pre>
   *
   * <code>string vpcUuid = 5;</code>
   */
  com.google.protobuf.ByteString
      getVpcUuidBytes();

  /**
   * <pre>
   *查询指定安全组下的dc2，sg UUID支持
   * </pre>
   *
   * <code>string sgUuid = 6;</code>
   */
  java.lang.String getSgUuid();
  /**
   * <pre>
   *查询指定安全组下的dc2，sg UUID支持
   * </pre>
   *
   * <code>string sgUuid = 6;</code>
   */
  com.google.protobuf.ByteString
      getSgUuidBytes();

  /**
   * <pre>
   *查询不在此sg下的dc2,默认为true, 需要与sgUuuid配合使用
   * </pre>
   *
   * <code>bool sgExclude = 7;</code>
   */
  boolean getSgExclude();

  /**
   * <pre>
   *查询指定dc2的信息,UUID
   * </pre>
   *
   * <code>repeated string dc2Uuids = 8;</code>
   */
  java.util.List<java.lang.String>
      getDc2UuidsList();
  /**
   * <pre>
   *查询指定dc2的信息,UUID
   * </pre>
   *
   * <code>repeated string dc2Uuids = 8;</code>
   */
  int getDc2UuidsCount();
  /**
   * <pre>
   *查询指定dc2的信息,UUID
   * </pre>
   *
   * <code>repeated string dc2Uuids = 8;</code>
   */
  java.lang.String getDc2Uuids(int index);
  /**
   * <pre>
   *查询指定dc2的信息,UUID
   * </pre>
   *
   * <code>repeated string dc2Uuids = 8;</code>
   */
  com.google.protobuf.ByteString
      getDc2UuidsBytes(int index);
}
