// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: compute/v1/vpc.proto

package com.didiyun.compute.v1;

public interface VpcAvailableCidrOrBuilder extends
    // @@protoc_insertion_point(interface_extends:didi.cloud.compute.v1.VpcAvailableCidr)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   *可用网段
   * </pre>
   *
   * <code>repeated string availableCidr = 1;</code>
   */
  java.util.List<java.lang.String>
      getAvailableCidrList();
  /**
   * <pre>
   *可用网段
   * </pre>
   *
   * <code>repeated string availableCidr = 1;</code>
   */
  int getAvailableCidrCount();
  /**
   * <pre>
   *可用网段
   * </pre>
   *
   * <code>repeated string availableCidr = 1;</code>
   */
  java.lang.String getAvailableCidr(int index);
  /**
   * <pre>
   *可用网段
   * </pre>
   *
   * <code>repeated string availableCidr = 1;</code>
   */
  com.google.protobuf.ByteString
      getAvailableCidrBytes(int index);
}
