// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: base/v1/base.proto

package com.didiyun.base.v1;

public interface JobInfoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:didi.cloud.base.v1.JobInfo)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   *任务Uuid
   * </pre>
   *
   * <code>string jobUuid = 1;</code>
   */
  java.lang.String getJobUuid();
  /**
   * <pre>
   *任务Uuid
   * </pre>
   *
   * <code>string jobUuid = 1;</code>
   */
  com.google.protobuf.ByteString
      getJobUuidBytes();

  /**
   * <pre>
   *资源Uuid
   * </pre>
   *
   * <code>string resourceUuid = 2;</code>
   */
  java.lang.String getResourceUuid();
  /**
   * <pre>
   *资源Uuid
   * </pre>
   *
   * <code>string resourceUuid = 2;</code>
   */
  com.google.protobuf.ByteString
      getResourceUuidBytes();

  /**
   * <pre>
   *任务进度，最大100
   * </pre>
   *
   * <code>double progress = 3;</code>
   */
  double getProgress();

  /**
   * <pre>
   *任务类型
   * </pre>
   *
   * <code>string type = 4;</code>
   */
  java.lang.String getType();
  /**
   * <pre>
   *任务类型
   * </pre>
   *
   * <code>string type = 4;</code>
   */
  com.google.protobuf.ByteString
      getTypeBytes();

  /**
   * <pre>
   *任务是否完成
   * </pre>
   *
   * <code>bool done = 5;</code>
   */
  boolean getDone();

  /**
   * <pre>
   *任务是否成功
   * </pre>
   *
   * <code>bool success = 6;</code>
   */
  boolean getSuccess();

  /**
   * <pre>
   *任务的详细结果,json需要不同情况解析
   * </pre>
   *
   * <code>string result = 7;</code>
   */
  java.lang.String getResult();
  /**
   * <pre>
   *任务的详细结果,json需要不同情况解析
   * </pre>
   *
   * <code>string result = 7;</code>
   */
  com.google.protobuf.ByteString
      getResultBytes();
}
